* Parasite Suite – A series of installations about networked experience and computational aesthetics.


** Introduction

The following works are a study in the way communication technology
influences artistic practice. The four pieces I have assembled draw attetnion to the relations between communications technology and musical production. It is my belief that communications technology has always had an intense impact upon musical practices and aesthetics, these works attempt to explore what the future of this relationship might hold.

On a personal level one piece of anecdotal evidence that I have
noticed is the large number of programmers and ICT (informatin
Communicatons Technolgy) workers that are musicians, composers or disc
jockeys. 

**** TODO Look up famous ppl doing both

One of the more interestng developments of the late 20th and early
21st century is the shift in the role of computing. Inititially
considered a tool limited to calculations and reckonings [fn:1], the
ability of computer to transmit and record has made it into a highly
effective communications tool. It is the tension between these two
roles, what I tend to think of as the tension between the database and
the signal, that I see exemplified in the contempory discourse about
surveilland and technology.[fn:2]

A computer can perform many roles, part of what makes general purpose machines interesting is their ability to be reconfigured. However that is not to say that the possibilities are limitless or easily explored. There are many things that are naturally difficult to do with general purpose computing for a wide variety of reasons that are too long to list. [fn:3] Furthermore, the manner in
which a product is designed, developed and organised, is often
specific to the workplace culture, organisation and mode of production
under which it originated. These kind of influences are likely to only
deepen rathr than disappear.[fn:4] A classic text describing this
scenario is the study by x.. 
*** TODO Find article about organisation culture I have

Many of the functions of modern society depend upon the computer not as a caculator but as a communications tool to relay messages. However in practice, the processes that allow communication to take place, message packaging, routing, encryption, transmittion and error checking are all based on the computation of algorithms. Because of the hybrididy of modern communication, both computational and networked, I have chosen to study how modern communication and musical practice can be interrelated.

As this project, determined in looking at 'possibilities', has a somewhat futuristic bent. I have elected to be somewhat wary of the degree to whih I cast the future in the mod eof my own emplacement. This circular inevitablility of conditioning my works into a kind of 'future-present' is somewhat inescapable. However in an attempt to mitigate this I have tried to take inspiriations for my work from other 'failed utopias' as much as the one I currently reside in.

In looking to early expectations and the failed dreams or unexplored possibilities of early omputer history, particulary notions of socialist computing, artificial intellignece, cybernetic surveilland and hippie counterculture, along with the ideas of modernist music composer such as Xenakis, Berio and Stochausen, who all had similar utopian notions about the future of both society and their art.

the cybersyn surveillance project of ALlende's Chile, the cybernetic counterculture of 1960's San Franciso and 

I have instead looked at other failed utopias. Since this work is a study in the effects of networking and computation. 

To do so iI have studied  

In order to look at some of the possibilities, it is necessary to apporximate 

A closer look at the terms involved part forms the basis for beginning this work. 

Exploring some of their neglected meanings and history of terms and contrasting that with where the emphasis of specific definition lies today is a key part of the work. By looking at the complete history and meaning of terms, particularly alternate meanings, I feel we can begin to excavate other possibilities, possibilities that were always available but feel cut off from now.  

For example, the word computer has a been on a historical journey from meaning a human being that makes calculations, to a device facilitation calculation. However even the interesting parts of that statement miss some of the socio-cultural aspects of what a being a computer means. 

For instance that computers were once large teams of people used in warfare to calculate distances, supplies and give reckonings for artillery. Or that later computers became numerical analysts, a job that was generally gendered to be for women, and teams of women were given the task of managing early machine-based computers. (Hmm prob not necessary, incl. refs). 

How to portray this rich and often conflicted history in a word is a difficult task. We see that  a key role for the artist can be excavating meaning. Looking that the meanings that have been applied over the years and following a common task in critical theory, asking why certain aspects have traditionally been ignore, or taken as a given. Because of this, to begin my process I have given in depth listings of the meaning of key terms for the suite of works.  A dictionary definition offer a reflection on the range of meaning and the suggest links to the history of what are seen as ‘modern’ terms. I am seeking to try and combine and undermine these terms to try and understand my own position. 

Networked, experience, computational, aesthetics and surveillance. 

Of these five terms the only term not given in the title of the study, ‘surveillance’ represents both the shadow of the other four terms and also what I suspect is the means to analyse and explore the possibilities of the other terms.  


* Footnotes

[fn:1]Find link
[fn:2] Something about why I think this

[fn:3] Here I am thinking about constraints like technical capabilty,
machinic power as well as cultural determinism, usability constraints
or challenges of imagination.

[fn:4] Ref to book on the desing of programs reflecting workplace.

