#+TODO: WRITE EDIT REVIEW | DONE DELETE
* DONE Introduction

*** networked experience and digital asethetics

    Parasite Suite is collection socially-orientated art works exploring human relations with technology, particularly the digital. The work is inspired by:  current anxieties about technology, particularly governmental surveillance, current critical studies of the digital, philosophical works on technology and information theory, as well as the works of modern composers with an interest in technology and society, such as...

*** Some of the key works for this study include ...

 The project is realised as a set of art projects that consider the premise that 'computationality' strongly influences our perception of the world. For humans, I believe the term 'computationality' can be broken into two components, a understanding of relations based on network, and a sympathy for thinking patterns are based on abductive reasoning.

* Abductive Reasoning
*** Abductive reasoning and computationality

Abductive reasoning is a an approach to logical reasoning that is somewhat novel and ubiquitous in its use by computer systems. It is a form of reasoning that is somewhat akin to 'guessing' based on pattern matching

'abductive' processes, when used by computers, allow them to work with 'fuzzy'; or flawed data sets using pattern recognition to try and match data sets to computer objects and subprocesses.

A mode of revealing  based on networking as its primary metaphor,

  An approach to the world through networking

  Approaches to the world through networking metaphors is a trend David Berry identifies in his book 'Critical Theory and Digital Criticism'[fn:46].

  worlds' 'Mode of Revealing' was closely related to  the use of technology as metaphor. Heidegger describes his times  mode of revealing 'challenging-forth', a notion Berry posits as based on the influence of modern physics and particularly electricity, where humans are placed as 'standing-reserve', and talked about in electrical metaphors suchh as 'potential'. berry declares a post-modern technology metaphor that has emerged based on 'Streaming-forth', a metaphor related to real-time networks[fn:2].

In the metaphor of 'streaming-forth'...

In a society experiencing constant engagment with software algorithms[fn:43] today's engagements with the world order themselves around the metaphor of a 'stream-forth' of engagements[fn:44]. This adoption of an attitude to the world based on technology is a concept described by Heidegger in his work 'The Question Concerning Technology'.[fn:45] He then relates the relationship of humans and technology to a kind of enframing (an all-emcompasing attitude to technology) that affects the use and development of other technologies, as well as informing a world view, becoming a kind of dangerous trap as it limits any further understanding of teh world beyond the metaphors of the technology in question. David Berry writes that Heidegger's examples are intentionally descriptive of an 'enframing' of electricity as its fundamental technology, with concepts like standing reserve (the notion of human action ready to be activiated) being based on the metaphor of voltage.

  The experience of considering oneself both a recipient and generator of the 'stream', is one of the defining characterstics of networked experience. If participants are indeed ordering their world in response to 'streams,' then typical goals include processing information, performing algorithmic transformations, and searching for ways to filter information to make it /computeable/, which leads into to our second quality of computationality, recognising patterns through abductive reasoning.

Abductive reasoning is a kind of 'guessing' the coresspondance of a data stream to a catalog of types that is quickly becoming the  b

* Pattern Recogniton

" Computers classify according to the patterns which have already been prorammed within them . Thus patterns serve to create a language, a /pattern language/, which is a set of classificatory means fo the identification of teh type of thing an object presentented to the computer is. Not the particular object, but the abstract calass of teh object and there fore the abstract pproperties and understandings that are pre-coded intot he computer and provide the bass of comprehension".


For example, , if I was to write a program that could recognise a pattern, say that you were reading this paragraph. In preparing to construct the algorithm I would consider what sensory inputs I have available, then design a solution

 and intention to read the paragraph that you are currently reading. A program might consist of a tracking of the


 in pseudocode

An important aspect to note is that this 'computational' mode of experience isn't dependant on any kind of technology or state of development in itself. As I have found in my research it is possible to create a networked experience based on streaming data and reactions based almost entirely on inter-human communication, as was the acase with the Cyber-Syn project in 1970s Chile[fn:41].

|--------------------+-----------------------------+---------------------------|
|                    | Technicity                  | Computationality          |
|                    | (modern technology)         | (postmodern technology)   |
|--------------------+-----------------------------+---------------------------|
| Mode of Revealing  | Challenging-forth (Gestell) | Streaming-forth           |
|--------------------+-----------------------------+---------------------------|
| Paradigmatic       | Technical devices,          | Computational devices     |
| Equipment          | machines                    | computers, processors.    |
|--------------------+-----------------------------+---------------------------|
| Goals (projects)   | 1. Unlocking                | 1. Trajectories           |
|                    | transforming                | Processng Info            |
|                    | storing                     | Algorithmic trans         |
|                    | distributing                | (aggregation, reduction   |
|                    | switching about             | calculation) as           |
|                    | Standing reseve             | /data reserve/            |
|                    | 2.efficiency                | 2. computability          |
|--------------------+-----------------------------+---------------------------|
| Identities (roles) | Ordered beings              | Streaming Beings          |
|--------------------+-----------------------------+---------------------------|
| Paradigmatic       | *Engineer* time motion      | *Design* Info theory      |
| Epistem            | studies, method-time        | graph theory              |
|                    | measurement (MTM)           | data viz                  |
|                    | instrument rationality      | communicative rationality |
|--------------------+-----------------------------+---------------------------|


* EDIT socialise and surveil


 Computationality can be defined as the ontotheology, of a specific historical 'epoch' (which we appear to be in at present) where by practices, methods and categories are based on an understanding that computers form part of our "essence and existence." In other words metaphors about computing make up a set of "knowledges, practices, methods and categories that 'temporarily secures the intelligible order[fn:1]'"
*************** Go into more detail about streaming
*************** END
'Computationality' can then be experienced as a combination of computer processing and networking capabilty that embody a particular aesthetic and mode of experience for those that interact with the works [fn:3]. The particulars of the experience and aesthetic of 'computationality' has been specifically collected and outlined by others[fn:4] but I loosely define it as the experiencne of a real world decision that seems influenced or larely determined by by what would be appropriate for the algorithmic sensibilities of a machine rather than a human sense of design aesthetic. The manner in which this is realised

     A particular aspect of the 'computational' I have focussed on is the felt sense that a machine can be treated as a participant and social actor rather than a tool.
*************** Examples
*************** END

*** EDIT
  An ontological shift towards sympathy for the machnines 'algorithmic' methods of understanding, mediating our own notions of beauty. The projects are intended to be open ended, generative and participatory, blurring lines between artist and audience. A key goal of the works is for proamming choices to affect dramatic shifts in  social roles and duties for participants. The concept is to place emphasis on the notion that a generalised  machine can constructed equally be a machine gun or a vacuum cleaner, or a collaborator or spy. Despite the outward presentation of a work or adoption of controversial digital 'features' such as data mining or monitoring,  technological systems are much more than hardware and code, they represent a,"'seamless web' of social, institutional and technological relationships.'"(122)It is the the heirachies and logistics of society that  play a crucial role in determining the material formation of a work[fn:5].

    The conceptual inspiration for these works is drawn from histories of early computing, the philosophical influence of early digital design, and cybernetic thought [fn:6], as well as philosophical works about technology and communication. [fn:7] Specific models and refereences for the works are outlined later in their descriptions and documentation. In general, it is the history of cultural metaphors about computation, as well as studies of  technological opportunities that never materialised or fell to the wayside, that have helped me to explore other possibilieties for social interaction in computing.[fn:8] By exploring these topics we can see interesting possibilities for restructuring networked engagements with machines. I wish to argue, as has been shown by Eden Medina in her study of some of the rudimentary techniques explored by the cyberneticians of the Cybersyn project in Allende's Chile, that it is not realtime communication of high tech computing that determines the sense of a 'networked experience', rather it is the idea of bi-directional streams of information that are being responded to. This idea is central in much of cybernetic organisational theory, and informs a wide range of practices today. One which I use extensively is the 'streams' programming technique, one that is prevalent in an extensive number of web programs at the moments.[fn:9]

*************** WRITE Go on more about audio
 In particular I have focused on the act of surveillance, a term that I am trying to explore beyond of its pejorative sense. Exploring the  term surveillance has allowed me to consider the thin line between social engagement and intelligence collection. Particularly when considering the perspective of a machine, it can be difficult to differentiate between methods that might enable new kinds of engagement and those that might alienate. In parasite one I have tried to design a surveilance model that offers two-way methods of remote listening by exploitng aspects of audio
*************** END

This term surveilance represents a useful union point between the machine and network, and implies a model of engagement based up monitoring and responding to interactions in a dynamic manner. For my studies it has come to represent a point of coalescence between the anxieties of today and an area of early study in the field of cybernetics. Particularly in the early era of computing, and similar to speculation about the possible uses of the phonograph[fn:10], cyberneticians were wildly imagining what a computer would be useful for. Certain unexpected innovations such as email also totally changed the field.

"E-mail emerged in 1971 when users began experimenting with ways of sending electronic messages from one networked computer to another. In her study of the Internet's origins, Janet Abbate writes that e-mail "remade" the ARPANET system and caused it to be see 'not as a computer system but rather as a communication sytem.'(ref.82) 1.[fn:11]

It is my belief that the notion of the usefulness for the computer in exploring musical, social and political possibilities can often be surprisingly limited. The key area of limitation I wish to explore is in the area of networked interaction between multiple agents. The key theme is essentially how the 'social' can be introduced into artistic and compositional practice.

The notion of the responsive surveillant, who may take on any biological or material form, is one of the cornerstone ideas of the field of cybernetics. We can see this biologically influenced notion otherwise known as a feedback system everywhere from the thermostat to many of the software 'daemons' of computers that operate in the backhand of UNIX based computers.[fn:12]

In these early experiments with the idea of 'what a compute should be', we can see the possibilities and disappointments of concepts such as like 'Socialist Computing', and efforts to radically reconsider the function of the computer when it is relevant to the culture and philosophy of disparate groups.

Artistically a reconsideration of the manner in which we interact with computers and each other under the banner of surveillance also represents a sincere attempt to portray some of the radical possibilities of computer art when it embraces its lineage and explores the anxieties of the present.

These three areas: the philosophies of how machinic interactions have coalesced into one commonly accepted into a common form, a look at unexplored possibilities and under-emphasised potentials in the present, and a search for how to revive those alternative futures, each represent the three strands of artistic research in the project.

I have attempted to unify these into four project.

It is a kind of consideration of the discrete and quantifiable that happens when we begin to employ a kind of empathy toward a machinic perspective.
*** EDIT
**** p1.
'immateriality of software[fn:13]'
Describes it as a /super-medium/ that unifies other forms,  (tv/film/radio/print), rather than containing them it reforms and reshapes them into a "new unitary form"[fn:14] "this super-medium acts as both a mediatingn and structuring frame that we must understand through its instantiation under particular physical constraints" - Rejecting the immateriality of software. Analysisng the doing, platform studies.

The terms 'softwarized society' coined by Dacid Berry [fn:15] encapsulates what I see as the outcome of networked experience and computational aesthetics. The term describes the impuct of computers on culture as both metaphor and (an often transparent) medium. {such as?} As technology inculcates itself we are indanger of forgetting how entangled with computer code we really are, it would be hard for me to think of any aspect of my daily life that isn't entangled within the world of software code, living within a nation dependant on software, and using it to write this exegesis. Software is part of the narrative of our lives, and yet often overlooked. Fuller (2006) notes, "in a sense, all intellecual work is now 'software study', in that the software provides its media and its context..." Berry encourages us to think about the "structure of feeling[fn:16]"  and methods of usefulness permitted by code. Noting that technology is a cultural metaphor as well as lexical and physical object. These varied cultural thoughts about technology in relation to the self and society inform practice and engagement with tools as well as wider social and economic relations. To the extent that Berry believes the metaphors of software in particular, to form a 'plane of immanance' that shapes relations[fn:17].
*** WRITE

By treating projects as socio-technical assemblages, connected to "broader networks of social relations and institutional ensembles"[fn:18]. I plan to
use technology as its own medium to consider the role of technologies. The intent is not to reject or provocate but to describe origins of human anxiety about the digitization of our world [fn:19].

As the context of the work is on social uses of technology, particul the manner in which  actors roles this can be manipulated within these, research for this project has involved histories of the social in computing. Within these histories, didactic and utopian attitudes to technology are rife, particularly in studying the histories of cybernetics, early personal-computing and 'socialist'-computing [fn:20].

However they it has tended to become apparent that the hopes and dreams of people like Stafford Beer and Stewart Brand are products of their of their time, in which the possibilities of new tools empowering users to create new worlds did seem real. This utopian bent make for interesting parellels with modern composers such as Stochasen and Xenakis, who exhibited similar attitudes about technology [fn:21].

it is this tension between the utopian attitudes of the past and some of the anxieites of the present. All of which belie the use of the same kinds of tchnology, which I wish to explore in these workds. My hypothesis is that there is a way through this, that within some of the most pervasively distressing manipulations of technology by governmet agencies and coverty actors[fn:22], there are techniques to reconsider the uses of technology once again if we look to some of these abandoned histories of computing.

*************** WRITE Para on theory
*************** END

With the hope to point out some of the heirachies and possbilities bestowed on different actors given certain combinations. The emphasis is on the social and collaborative aspects that are possbile, with their attendant possibilities for exploitation, re-working and misuse both creative and destructive.

One particuular kind of technological assemblage that is commonly known to provoke feelings of anxiety about the digital, is techniques of surveillance[fn:23]  , can have their heirachies and processes changed to give power to new actors and outcomes.

These projects, which try to take the same materials and processes of the anxiety inducing technologies in question are somewhat foregone in their conclusion that is often the heightened ability of established heirachies and actors to utilise these tools for ill will rather than the technic itself.

In my attempt to consider the design and implementation of tools like computer vision, real-time communication and data-colleciton, I have often found that the design and user experience as a developer is often imprinted with the culture and expectations of the teams that assembled the foundations of these tools[fn:24]. In a sense I have discovered  a source for my own anxiety in a consciousness of the kind of corporate cultures values embedded in the design of systems. My response to this has been to try and configure atypical user interfaces and methods of engagement, such as avoiding teh user metaphor of a person sitting at a computer terminal with keyboard and mouse, and trying to treat sound as a first-class user interaction medium[fn:25].


In this sense the work is inspired by coucpets such as 'sousveillance'[fn:26] where a technology is leveled against an oppressor rather than the opposite. In my course of exploring how to 'turn the tables' however, I have also found that it is often the composition of technologies and the relationships that their design encourages[fn:27], that require the formulation of organic and locally specific technologies that offer solutions more relevant in my case for an artistically inpired, more affecting outcome, and on a general level benefit participants.

*** TODO Quote about subroutines and influence on programming[fn:28].


However the process by which I developed this project was not from a carefully chosen theme, but rather a methodoology where I have sought to describe some of the 'back boxes' of communications that I interact with on a daily basis. My methodology for investigating something like data-collection, monitoring and signal intelligence is derived from creating a project that mimics a small subset of these behaviors in an uncommon context, and then noting the processes that are fundamental to the existence of the 'machine'. This method involves treating the world in a manner very simlar to the concept of a 'function', otherwise known as a subroutine in computer programming. In some way I am attempting to import concepts from a pradigm in computer programming, 'functional programming'

Many interesting things can be said about

. It just so happens that when I consider some of the inherant qualities of the manner in which I would conduct myself, even in moments that I step away from a 'screen', the encounters of my life are all deeply network driven. One of the discoveries of early computing i sthat computational speed makes vastly wider and new kinds of networks possible.[fn:29]
Pattern Aesthetic-

*** TODO Quote about discovery of email from Cybersyn[fn:30]


**** In previous projects I have explored the strangeness of everyday objects, using sound as a  tool for the expression of a-human sentiment? :kill:

If I was to describe a common daily schedule for the period over which I have been working on these projects, it would be a highly computational one. However even if I was to completely to withdraw, to refuse to acknowledge how much of life is order by the twin processes of networking and computation. I would stil be embedded in a system in which my birt[fn:31]h, sustenance[fn:32],

I wake daily, and usually the first thing I do is check my emails. After that I eat, drink coffee and walk to my studio. There I will usually spend the first two hours reasearching, either reading books on a relevant topic or trying to follow any blog posts or online tutorials about the technical aspects of the 'black boxes' that are the technical building blocks of my projects.


** Networked Experience

My definition is an embodied process of understanding that takes place across a network. Some of the times one might typically include the remote administration of computers, multi-user collaboration on documents (as seen in services like google docs), or even on a  more basic level telecommunications services of all kinds that allow for two way interaction.

Here we notice that the technologies that *offer* networked experience as a technology are unlimited, but it is the situations in which it becomes a *practice* which are interestion to me. What defines the practice is the interaction of more than one participant and the aspect of message communication as a tool rather than crafting.

What I am particlarly interested in is mutual real-time meaning making between multiple particpants or kinds of actors.

** Inspirations

The inspiriation is taken from Serres concept of 'black boxing'. Seeing the world in terms of components. Taking one and stripping away layers of abstraction in order to understand the processes involved, then returning the 'box' to its position  with newfound understanding.

In my case I am looking at the current state of human relations as I experience them. I am particularly focussed on the 'machinic' qualities and the managemnt of what is commonly thought of as mediation, and common anxieties and concerns with current engagement. I am usingtools that seem applicable and the easiest and most relevant to the concerns. typically the same materials such as, web page scripting, electronic components and sensory inputs and outputs, that are involved in the 'black box'.

So while the work might seem at first technical in nature. I am more interested in trying to 'simply' understand a set of relations and use audio as a descriptive tool.


The four art installations I have assembled represent a set of considerations about how music and technology should interact, and of what this might mean for wider attitudes about the role of the computer in music and society at large.

*** TODO
** How we got to

   My research has been into the technologi]cal ideologies that have shaped attitudes to the use of computers in music. Particularly the lineage of political strains Romantic Individualism and utopianism that beacame a part of the ethos of what is know as "The California Ideology"[fn:33] This fusion of various strains of thought among academics and inventors after World War Two would go on to shape many aspects of the design and research into the use of computers that we continue to use today.[fn:34]

Similarly to the cyberneticians, counterculturaliststs and techno-utopians, I wish to explore the interaction of sytems and tools and how the relate.

However in the field of music has at times been both highly influential, as Fred Turner argues that the use of rock music and stereo equipment as a 'mind expanding' tool was highly influential on the design of the computer.

However the notion of computer music has also offered a challenge for software designers to offer a satisfactory interface for,

it has also at times offered a challenge to the

It is my argument that aspects of thinking about how computers should be used in art and music are limited by ideological constraints on the kinds of interaction that can be permitted.

The lineage of the the 'california ideology' on interaction with computers today seems to enforce the idea of engagement witha  computer being focused on having one operator, holding tight deterministic control over one program utilising an acceptable set of input and output techniques.

However rather than attempting to completely divorce myself from this lineage or propose my own utopia. I wish to make a study of these forces of technoligical ideology and incorperate it into my artworks. By blending representations of the problematic lineage and present state of paranoia with other utopian visions of computing that never quite made it. As well as some of my own ideas about what might be possible in the realm of collaborative experience and new and experimental engagement with machines, others and ourselves. I hope to reintroduce political ideas into the discussion of technology by reintroducing the social and political into the musical and technological landscape.

I argue that there is a link between some aspects of the transhumanism which has influenced much of technological design and desires of transcendence in 20th century music compoers such as John Cage that has emphaised transcendce at he expese of 'silencing the social' in the wods of Douglas Kahn. It is not my wish to decry these works, rather to celebrate and reconsider them in the context of today where we are never sure if we are too connected and being surveilled, or too alone and alienated. Instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there Instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there.

** TODO Unexplored Futures

** TODO Future Interfacing



I feel that my work is a kind of physical reaserch into the terms of contention and the possibilites they might offer. i feel that difficult, negative or contentious terms are not as exhausted or pre-determined in meaning as we might imagine.

 of one vision of computing with some of the other

As well as considering the ideaologies and politics that have informed the design of our 'tools', the works look at the ideas about appropriate aesthetics


as well as the aesthetics of the msucial landscape that those tools, their operators and composers help create.

It is my conjecture that in followng the history of early computing and developments in musical technolgy, we can see how the culture of three areas in western culture, military industrial and academic, became a key part of what I have termed 'contract culture' in the world after world war two.

The following works are a study in the relationship and possibilities in the spaces between communication technology and artistic practice.

Communications technology and musical practice hold much in the way of a common history, converging and

albeit a

 practcie, tradition and aesthetics. From the use of drums as a signalling tool, or even drum languages [fn:35] to the development of brass instruments for

and aesthetics, these works attempt to explore what the future of this relationship might hold.

**

On a personal level one piece of anecdotal evidence that I have noticed is the large number of programmers and ICT (informatin Communicatons Technolgy) workers that are musicians, composers or disc
jockeys.

*** TODO Look up famous ppl doing both

Links between player piano and loom.


*** TODO History of ICT links to music tech


One of the more interestng developments of the late 20th and early
21st century is the shift in the role of computing. Inititially
considered a tool limited to calculations and reckonings [fn:30], the
ability of computer to transmit and record has made it into a highly
effective communications tool. It is the tension between these two
roles, what I have started to think of as a tension between two different models for the organisation of information as outlined by De Landa..

of in the heirachy of information organisation and transmission that is deeply explored in

between the signal and database, that I see exemplified in the contempory discourse about
surveilland and technology.[fn:29]

A computer can perform many roles, part of what makes general purpose machines interesting is their ability to be reconfigured. However that is not to say that the possibilities are limitless or easily explored. There are many things that are naturally difficult to do with general purpose computing for a wide variety of reasons that are too long to list. [fn:36] Furthermore, the manner in
which a product is designed, developed and organised, is often
specific to the workplace culture, organisation and mode of production
under which it originated. These kind of influences are likely to only
deepen rathr than disappear.[fn:37] A classic text describing this
scenario is the study by x..
*** TODO Find article about organisation culture I have

Many of the functions of modern society depend upon the computer not as a caculator but as a communications tool to relay messages. However in practice, the processes that allow communication to take place, message packaging, routing, encryption, transmittion and error checking are all based on the computation of algorithms. Because of the hybrididy of modern communication, both computational and networked, I have chosen to study how modern communication and musical practice can be interrelated.

As this project, determined in looking at 'possibilities', has a somewhat futuristic bent. I have elected to be somewhat wary of the degree to whih I cast the future in the mod eof my own emplacement. This circular inevitablility of conditioning my works into a kind of 'future-present' is somewhat inescapable. However in an attempt to mitigate this I have tried to take inspiriations for my work from other 'failed utopias' as much as the one I currently reside in.

In looking to early expectations and the failed dreams or unexplored possibilities of early omputer history, particulary notions of socialist computing, artificial intellignece, cybernetic surveilland and hippie counterculture, along with the ideas of modernist music composer such as Xenakis, Berio and Stochausen, who all had similar utopian notions about the future of both society and their art.

the cybersyn surveillance project of ALlende's Chile, the cybernetic counterculture of 1960's San Franciso and

I have instead looked at other failed utopias. Since this work is a study in the effects of networking and computation.

To do so iI have studied

In order to look at some of the possibilities, it is necessary to apporximate

A closer look at the terms involved part forms the basis for beginning this work.

Exploring some of their neglected meanings and history of terms and contrasting that with where the emphasis of specific definition lies today is a key part of the work. By looking at the complete history and meaning of terms, particularly alternate meanings, I feel we can begin to excavate other possibilities, possibilities that were always available but feel cut off from now.

For example, the word computer has a been on a historical journey from meaning a human being that makes calculations, to a device facilitation calculation. However even the interesting parts of that statement miss some of the socio-cultural aspects of what a being a computer means.

For instance that computers were once large teams of people used in warfare to calculate distances, supplies and give reckonings for artillery. Or that later computers became numerical analysts, a job that was generally gendered to be for women, and teams of women were given the task of managing early machine-based computers. (Hmm prob not necessary, incl. refs).

How to portray this rich and often conflicted history in a word is a difficult task. We see that  a key role for the artist can be excavating meaning. Looking that the meanings that have been applied over the years and following a common task in critical theory, asking why certain aspects have traditionally been ignore, or taken as a given. Because of this, to begin my process I have given in depth listings of the meaning of key terms for the suite of works.  A dictionary definition offer a reflection on the range of meaning and the suggest links to the history of what are seen as ‘modern’ terms. I am seeking to try and combine and undermine these terms to try and understand my own position.

Networked, experience, computational, aesthetics and surveillance.

Of these five terms the only term not given in the title of the study, ‘surveillance’ represents both the shadow of the other four terms and also what I suspect is the means to analyse and explore the possibilities of the other terms.
*** Issues w/ thinking of sound based art-work as 'time based media'
    If installation is not a processional peice, w/ beginning and end, where does that situate sound? Digital influence. Is adaptive/ generative sound still time based? Is it more real time and responsive?
* Footnotes

[fn:3] link to uses of term 'Computationality'

[fn:15] Softwareised Society, Link opening of Phil of Software on dependance on software for survival. Berry p. 18

[fn:24] link to classic essay about design of saftware informed culture

[fn:25] Any links to this? There was a bit from Deland somewhere.

[fn:19] Software is eating the world

[fn:23] Def of Surveillance

[fn:26] Sousveilance link

[fn:27] Foucoult link, design of software and oppression

[fn:28] Functions in programming.

[fn:29] Computers and Society

[fn:30] Cybernetic Revolutionaries

[fn:31] design of medical monitoring machines (see berry)

[fn:32] Everything from the control of crops to the management of wild environments and  population control of wild species

[fn:8] Idea taken from the talk,"The Web that wasn't" )[[webthatwasnt][TWTW]]

[fn:12] Whats a daemon yo.

[fn:33] Link to[[http:hrc.wmin.ac.uk/theory-californianideology.html][Barbroo, Cameron - Hypermedia Research Centre

[fn:34] Examples: Skeudomorphic design, interactinon models. Give more

[fn:35] REf to drum languages

[fn:36] Here I am thinking about constraints like technical capabilty,
machinic power as well as cultural determinism, usability constraints
or challenges of imagination.

[fn:37] Ref to book on the desing of programs reflecting workplace.

[fn:20] Link to treer main history book / topics

[fn:21] Stoch to Xenakis quote

[fn:22] Link five eyes surveillance

[fn:18] Berry p.62

[fn:17] Berry and Deleuze, p. 18.

[fn:16] Berry, p. 6.

[fn:13] Berry 10

[fn:14] Berry 10

[fn:5] Idea inspired by Frocki's first film.

[fn:4] link to New Aesthetic site / files

[fn:6] Link to Weiner

[fn:7] Link De Landa, Berry.

[fn:10] Article about uses of early phonograph

[fn:38] Cybersyn 95

[fn:39] Cyber to Counter 259k

[fn:9] link to deetails on javascript streams

[fn:11] Edina 64

[fn:1] Thomson 2009 149-150.

[fn:2] [[http://stunlaw.blogspot.co.uk/2011/11/world-of-computationality-flickering.html][The World of Computationality: Flickering Objects and Streaming-beings]]

[fn:40] Ontotheology - See Heidegger

[fn:41] REf to dependdence on human actors in Cybersyn

[fn:42] Define what technicity is

[fn:43] Expampeles of constant engagement w/ algorithms especially in many processes that we consider as being 'away from the computer' For instance the production and shipping of any good is now entirely dependant on real time monitoring and 'just in time' production.

[fn:44] Berry (2011), an avid reader of Martin Heidegger, argues that in contrast to the /technnicity[fn:42]/ of electricity that ordered the /mode of revealing/ of Heidegger's world,

[fn:45] Heidegger and technology

[fn:46] wtf is this book called
