#+TODO: WRITE EDIT REVIEW | DONE DELETE
* Intro Quote
/we know very little about the ways in which software is socially created, the nature of software itself; how discourse, practices, and knowledge get translated into algorithms and code; the geographies and political economy of software development; how software is embedded into various social systems; how software applications work with each other to create complex assemblages that work within and across scales; the power wielded through software's "secondary agency"; and how software alternativly modulates the production production of space and transforms the nature of governance. (Kitchin 2011: 946)/
* EDIT Introduction
** DONE Networked Experience and Digital Asethetics
*** Is there a digital subconscious?
   Parasite Suite is collection of socially-orientated art works exploring human relations with technology. The works are inspired by anxieties about technology, (particularly government and institutional surveillance), critical studies of the digital, philosophical works on technology and information theory, as well as works by composers with an interest in the relationship between technology and society. The project is realised as a set of art projects that consider the shape of social engagements for those adopting a 'computational' mindset.

** REVIEW Enframing - Two aspects to the computational

Enframing is "the essence of modern technology[fn:1]", a relationship we are in with technology influences our understanding of truth.

     The idea of a 'computational' society describes an attitude and understanding of the world mediated by the use of technology, a notion similar to Heidegger's notion of 'enframing.' [fn:2] In "The Question Concerning Technology"[fn:3], 'enframing' describes not only how technology mediates our engagements with the world, but also how characteristics of technologies are adopted as metaphor for other sytems, paticularly the economic and social. Taken further, a technologies 'mode-of-revealing' becomes a kind of subconscious influence in our attitude toward the world, similar to what is described in the mantra "the medium is the metaphor" by Neil Postman[fn:4].

*************** WRITE Go into more about Postman
*************** END

     This psychological adoption of an attitude toward the world based on technology is a sceanario described by Heidegger in his work 'The Question Concerning Technology'.[fn:5] Heidegger relates one aspect of the relationship between humans and technology as 'enframing', where the inner and outer world is influenced by technology. Affecting use and development of other technologies, as well as informing a world view, becoming a kind of inescapable trap that might limit further understanding of the world beyond the developing of the technology in question. In this sense we have a symbiotic, yet parasitic relationship with technology, we see it as a way to advance and master a domain, and yet doing so dominates our thinking with the technologies limited number of approaches. As one of the goals of software seems to be to adopt a constructionist 'realness'[fn:6], it can be particularly hard to notice its presence as it aspires to transparancy, there are thus two kinds of disappearances technology tries to make, the first a sense of the natural to try and minimize its presence, and the second a appeal to transparency that deflects the notion that anything was to be hidden in the first place.

*************** WRITE check what notion of 'stranding-reserve' means
*************** END

*************** WRITE Enframing examples...
*************** END

In this respect human relationships with technology occupy a somewhat vexed space, with technology seen as both 'means to an end', a tool of progress or improvement, yet perhaps more importantly technology is also a medium through which we experience the world. I hope to analyse this by designing engagments that at appear to prioritize technicity but on further involvement derive their functions from the technological mediation of a social scenario. I wish to ecnourage critical approaches to thinking about and responding to digital culture beyond the purely technnical spheres in which it is often discussed.

*************** WRITE some key works for this study include
such as John Cage and Iannis Xenakis.?
*************** END

   'Computationality' as an elaboration of what Heidegger describes as 'enframing', developed by David Berry.  David Berry writes that Heidegger's notion of enframing is intentionally use electricity and modern physics as its fundamental technological metaphors, with concepts like standing-reserve, the notion of human action ready to be activiated being based on the metaphor of voltage. The notion of 'computationality', is corresponding based on the language of the network and the aesthetics of software engineering.

*************** Categories of affect(?) in  berry's classification table
*************** END

|--------------------+-----------------------------+---------------------------|
|                    | technicity                  | computationality          |
|                    | (modern technology)         | (postmodern technology)   |
|--------------------+-----------------------------+---------------------------|
| mode of revealing  | challenging-forth (gestell) | streaming-forth           |
|--------------------+-----------------------------+---------------------------|
| paradigmatic       | technical devices,          | computational devices     |
| equipment          | machines                    | computers, processors.    |
|--------------------+-----------------------------+---------------------------|
| goals (projects)   | 1. unlocking                | 1. trajectories           |
|                    | transforming                | processng info            |
|                    | storing                     | algorithmic trans         |
|                    | distributing                | (aggregation, reduction   |
|                    | switching about             | calculation) as           |
|                    | standing reseve             | /data reserve/            |
|                    | 2.efficiency                | 2. computability          |
|--------------------+-----------------------------+---------------------------|
| identities (roles) | ordered beings              | streaming beings          |
|--------------------+-----------------------------+---------------------------|
| paradigmatic       | *engineer* time motion      | *design* info theory      |
| epistem            | studies, method-time        | graph theory              |
|                    | measurement (mtm)           | data viz                  |
|                    | instrument rationality      | communicative rationality |
|--------------------+-----------------------------+---------------------------|

** EDIT Networked Experience: - both mode of revealing and identity

   Networked Experience is both the use, and outlook on the world, based on metaphors that expect the world to be seen through the prism of networked communication systems. It is an approach to the world [fn:7] based on the 'network-as-metaphor', is an attitude that has been described by both Martin Heidegger and Neil Postman, I am defining this as 'networked-experience'. Heidegger argues that the essence of technology is not located in the machine but the human 'frame of mind' that allows both its production and shapes the ordering of things that allows a wider changes to come into being. Heidegger considers the relationship between humanity and technology as a frame that shapes engagements with the world, in his terms 'enframing' all other perceptual processes[fn:8].

In Heidegger's case he describes this 'enframing' of his times are based upon the influence of electricity and modern physics. Humans are situated as 'standing-reserve', and talked about in electrical metaphors such as 'potential'. David Berry seeks to expand upon Hedegger's theory and argues that a new 'enframing' is based on the digital uses the network as its primary metaphor. where revealing is seen in terms of 'streaming forth' and actions are seen in algorithmic, graphic terms closely related to data-science. Similarly Neil Postman wrote that the 'Medium is the Metaphor', in a twist on Marshall Mcluhan's work. By this he intended to convey something very similar to Heidegger, that the technologes which provide access to information have an even more pervasive influence on our attitudes and understandings of the world than McLuhan's message.

*************** WRITE Eleborate on Postman
*************** END
*************** WRITE Examples of medium as metaphor
For some examples of this, I was recently listening to a podcast where a software developer who uses Agile software development organisational theory practices to manage his family.
*************** END
*************** write example of soundcloud as stream

  the experience of considering oneself both a recipient and generator of the 'stream', is one of the defining characterstics of networked experience. if participants are indeed ordering their world in response to 'streams,' then typical goals include processing information, performing algorithmic transformations, and searching for ways to filter information to make it /computeable/, which leads into to our second quality of computationality, recognising patterns through abductive reasoning.

*************** Identities as 'Streaming Beings'
*************** END

** EDIT Abductive reasoning:- paradigm, goal, paradigmatic epistem


 Abductive reasoning is a an approach to reasoning, ubiquitous for computer systems. It is most often used when trying to make judgements working with 'fuzzy' or flawed data sets. It can be compared to deductive (logic, proof-based) and inductive (probable, evidence based), as the 'fuzziest' kind of reasoning, somewhat akin to a 'best guess'. Abductive reasoning attempts to guess based on the information at hand, refining the set of best guesses as the quality improves or amount of data accumulates. one of the most well known examples included predictive text, other more complex examples have been shown by the google corperation, such as autocomplete suggestions[fn:46], early work on abductive resoning in computers was highly focussed on artificial intelligence[fn:47].

*************** abductive reasoning in real life...
*************** end


** WRITE computationality - our pattern language

/There is evidence that people naturally respond to computers as if they were people. When they work well, we think of them as teammates, and when they are obstinate or rude, we respond to them the same way we respond to rude, obstinate people (Reeves and Nass, The Media Equation: How People Treat Computers, Television, and New Media Like Real People and Places)./ [fn:48]

   When networked experiences and abductive coalesce in the form of 'computationality', the resulting medium of experience can be described as a form of a 'pattern language'. A 'pattern language' is something that we can be aware of, but whose methods tries to make itself 'transparent' to us. this appeal to transparency goes beyond the user interface level into all manner of abstractions at all levels of coded space: interfaces, application programming interfaces(apis), objects, macros, function composition, integrated circuits, all exist as abstractions that can make an processes result seem more natural when they hide away complexity. these toos are crucial for managing all of my projects, however the cumulative effect of these tools, often appears as a kind of 'magic' to the person using the tool to prepare an experience, and as a kind of faux 'natural' to the end user, who is intended to be none the wiser.

*************** end

*************** write on philosophy of software - constructionism
"this frantic disorientation uderneath the surface is therefor insulated from the user, who is provided with an interactional surface that can be familiar, skeudomorphic, representational, metonymic, flat, figurative or extremely simplistic and domestic."
*************** end


an important aspect to note is that this 'computational' mode of experience isn't dependant on any kind of technology or state of development in itself. as i have found in my research it is possible to create a networked experience based on streaming data and reactions based almost entirely on inter-human communication, as was the acase with the cyber-syn project in 1970s chile[fn:9].


   " computers classify according to the patterns which have already been prorammed within them . thus patterns serve to create a language, a /pattern language/, which is a set of classificatory means fo the identification of the type of thing an object presentented to the computer is. not the particular object, but the abstract calass of teh object and there fore the abstract pproperties and understandings that are pre-coded intot he computer and provide the bass of comprehension".

*************** pattern example
#+begin_src javascript
// sensor inputs, mouse cursor postition, page location,

#+end_src
*************** end

   for example, if i was to write a program that could recognise a pattern, say that you were reading this paragraph. i would first have to consier /how/ you were reading the text, both the phsysical device and medium. for instance in a book, on  a tablet or mobile device or on a computer
 in preparing to construct the algorithm i would consider what sensory inputs i have available, then design a solution
 and intention to read the paragraph that you are currently reading. a program might consist of a tracking of the

*************** personal example of emplacement
*************** end

** write socialise and surveil

'computationality' can then be experienced as a combination of computer processing and networking capabilty that embody a particular aesthetic and mode of experience for those that interact with the works [fn:10]. the particulars of the experience and aesthetic of 'computationality' has been specifically collected and outlined by others[fn:11] but i loosely define it as the experiencne of a real world decision that seems influenced or larely determined by by what would be appropriate for the algorithmic sensibilities of a machine rather than a human sense of design aesthetic. the manner in which this is realised

     a particular aspect of the 'computational' i have focussed on is the felt sense that a machine can be treated as a participant and social actor rather than a tool.
*************** examples
		*************** end

*** edit
  an ontological shift towards sympathy for the machnines 'algorithmic' methods of understanding, mediating our own notions of beauty. the projects are intended to be open ended, generative and participatory, blurring lines between artist and audience. a key goal of the works is for proamming choices to affect dramatic shifts in  social roles and duties for participants. the concept is to place emphasis on the notion that a generalised  machine can constructed equally be a machine gun or a vacuum cleaner, or a collaborator or spy. despite the outward presentation of a work or adoption of controversial digital 'features' such as data mining or monitoring,  technological systems are much more than hardware and code, they represent a,"'seamless web' of social, institutional and technological relationships.'"(122)it is the the heirachies and logistics of society that  play a crucial role in determining the material formation of a work[fn:12].

    the conceptual inspiration for these works is drawn from histories of early computing, the philosophical influence of early digital design, and cybernetic thought [fn:13], as well as philosophical works about technology and communication. [fn:14] specific models and refereences for the works are outlined later in their descriptions and documentation. in general, it is the history of cultural metaphors about computation, as well as studies of  technological opportunities that never materialised or fell to the wayside, that have helped me to explore other possibilieties for social interaction in computing.[fn:15] by exploring these topics we can see interesting possibilities for restructuring networked engagements with machines. i wish to argue, as has been shown by eden medina in her study of some of the rudimentary techniques explored by the cyberneticians of the cybersyn project in allende's chile, that it is not realtime communication of high tech computing that determines the sense of a 'networked experience', rather it is the idea of bi-directional streams of information that are being responded to. this idea is central in much of cybernetic organisational theory, and informs a wide range of practices today. one which i use extensively is the 'streams' programming technique, one that is prevalent in an extensive number of web programs at the moments.[fn:16]

*************** write go on more about audio
 in particular i have focused on the act of surveillance, a term that i am trying to explore beyond of its pejorative sense. exploring the  term surveillance has allowed me to consider the thin line between social engagement and intelligence collection. particularly when considering the perspective of a machine, it can be difficult to differentiate between methods that might enable new kinds of engagement and those that might alienate. in parasite one i have tried to design a surveilance model that offers two-way methods of remote listening by exploitng aspects of audio
*************** end

this term surveilance represents a useful union point between the machine and network, and implies a model of engagement based up monitoring and responding to interactions in a dynamic manner. for my studies it has come to represent a point of coalescence between the anxieties of today and an area of early study in the field of cybernetics. particularly in the early era of computing, and similar to speculation about the possible uses of the phonograph[fn:17], cyberneticians were wildly imagining what a computer would be useful for. certain unexpected innovations such as email also totally changed the field.

"e-mail emerged in 1971 when users began experimenting with ways of sending electronic messages from one networked computer to another. in her study of the internet's origins, janet abbate writes that e-mail "remade" the arpanet system and caused it to be see 'not as a computer system but rather as a communication sytem.'(ref.82) 1.[fn:18]

it is my belief that the notion of the usefulness for the computer in exploring musical, social and political possibilities can often be surprisingly limited. the key area of limitation i wish to explore is in the area of networked interaction between multiple agents. the key theme is essentially how the 'social' can be introduced into artistic and compositional practice.

the notion of the responsive surveillant, who may take on any biological or material form, is one of the cornerstone ideas of the field of cybernetics. we can see this biologically influenced notion otherwise known as a feedback system everywhere from the thermostat to many of the software 'daemons' of computers that operate in the backhand of unix based computers.[fn:19]

in these early experiments with the idea of 'what a compute should be', we can see the possibilities and disappointments of concepts such as like 'socialist computing', and efforts to radically reconsider the function of the computer when it is relevant to the culture and philosophy of disparate groups.

artistically a reconsideration of the manner in which we interact with computers and each other under the banner of surveillance also represents a sincere attempt to portray some of the radical possibilities of computer art when it embraces its lineage and explores the anxieties of the present.

these three areas: the philosophies of how machinic interactions have coalesced into one commonly accepted into a common form, a look at unexplored possibilities and under-emphasised potentials in the present, and a search for how to revive those alternative futures, each represent the three strands of artistic research in the project.

i have attempted to unify these into four project.

it is a kind of consideration of the discrete and quantifiable that happens when we begin to employ a kind of empathy toward a machinic perspective.
*** edit
**** p1.
'immateriality of software[fn:20]'
describes it as a /super-medium/ that unifies other forms,  (tv/film/radio/print), rather than containing them it reforms and reshapes them into a "new unitary form"[fn:21] "this super-medium acts as both a mediatingn and structuring frame that we must understand through its instantiation under particular physical constraints" - rejecting the immateriality of software. analysisng the doing, platform studies.

the terms 'softwarized society' coined by dacid berry [fn:22] encapsulates what i see as the outcome of networked experience and computational aesthetics. the term describes the impuct of computers on culture as both metaphor and (an often transparent) medium. {such as?} as technology inculcates itself we are indanger of forgetting how entangled with computer code we really are, it would be hard for me to think of any aspect of my daily life that isn't entangled within the world of software code, living within a nation dependant on software, and using it to write this exegesis. software is part of the narrative of our lives, and yet often overlooked. fuller (2006) notes, "in a sense, all intellecual work is now 'software study', in that the software provides its media and its context..." berry encourages us to think about the "structure of feeling[fn:23]"  and methods of usefulness permitted by code. noting that technology is a cultural metaphor as well as lexical and physical object. these varied cultural thoughts about technology in relation to the self and society inform practice and engagement with tools as well as wider social and economic relations. to the extent that berry believes the metaphors of software in particular, to form a 'plane of immanance' that shapes relations[fn:24].
*** write

by treating projects as socio-technical assemblages, connected to "broader networks of social relations and institutional ensembles"[fn:25]. i plan to
use technology as its own medium to consider the role of technologies. the intent is not to reject or provocate but to describe origins of human anxiety about the digitization of our world [fn:26].

as the context of the work is on social uses of technology, particul the manner in which  actors roles this can be manipulated within these, research for this project has involved histories of the social in computing. within these histories, didactic and utopian attitudes to technology are rife, particularly in studying the histories of cybernetics, early personal-computing and 'socialist'-computing [fn:27].

however they it has tended to become apparent that the hopes and dreams of people like stafford beer and stewart brand are products of their of their time, in which the possibilities of new tools empowering users to create new worlds did seem real. this utopian bent make for interesting parellels with modern composers such as stochasen and xenakis, who exhibited similar attitudes about technology [fn:28].

it is this tension between the utopian attitudes of the past and some of the anxieites of the present. all of which belie the use of the same kinds of tchnology, which i wish to explore in these workds. my hypothesis is that there is a way through this, that within some of the most pervasively distressing manipulations of technology by governmet agencies and coverty actors[fn:29], there are techniques to reconsider the uses of technology once again if we look to some of these abandoned histories of computing.

*************** write para on theory
*************** end

with the hope to point out some of the heirachies and possbilities bestowed on different actors given certain combinations. the emphasis is on the social and collaborative aspects that are possbile, with their attendant possibilities for exploitation, re-working and misuse both creative and destructive.

one particuular kind of technological assemblage that is commonly known to provoke feelings of anxiety about the digital, is techniques of surveillance[fn:30]  , can have their heirachies and processes changed to give power to new actors and outcomes.

these projects, which try to take the same materials and processes of the anxiety inducing technologies in question are somewhat foregone in their conclusion that is often the heightened ability of established heirachies and actors to utilise these tools for ill will rather than the technic itself.

in my attempt to consider the design and implementation of tools like computer vision, real-time communication and data-colleciton, i have often found that the design and user experience as a developer is often imprinted with the culture and expectations of the teams that assembled the foundations of these tools[fn:31]. in a sense i have discovered  a source for my own anxiety in a consciousness of the kind of corporate cultures values embedded in the design of systems. my response to this has been to try and configure atypical user interfaces and methods of engagement, such as avoiding teh user metaphor of a person sitting at a computer terminal with keyboard and mouse, and trying to treat sound as a first-class user interaction medium[fn:32].


in this sense the work is inspired by coucpets such as 'sousveillance'[fn:33] where a technology is leveled against an oppressor rather than the opposite. in my course of exploring how to 'turn the tables' however, i have also found that it is often the composition of technologies and the relationships that their design encourages[fn:34], that require the formulation of organic and locally specific technologies that offer solutions more relevant in my case for an artistically inpired, more affecting outcome, and on a general level benefit participants.

*** todo quote about subroutines and influence on programming[fn:35].


however the process by which i developed this project was not from a carefully chosen theme, but rather a methodoology where i have sought to describe some of the 'back boxes' of communications that i interact with on a daily basis. my methodology for investigating something like data-collection, monitoring and signal intelligence is derived from creating a project that mimics a small subset of these behaviors in an uncommon context, and then noting the processes that are fundamental to the existence of the 'machine'. this method involves treating the world in a manner very simlar to the concept of a 'function', otherwise known as a subroutine in computer programming. in some way i am attempting to import concepts from a pradigm in computer programming, 'functional programming'

many interesting things can be said about

. it just so happens that when i consider some of the inherant qualities of the manner in which i would conduct myself, even in moments that i step away from a 'screen', the encounters of my life are all deeply network driven. one of the discoveries of early computing i sthat computational speed makes vastly wider and new kinds of networks possible.[fn:36]
pattern aesthetic-

*** todo quote about discovery of email from cybersyn[fn:37]


**** in previous projects i have explored the strangeness of everyday objects, using sound as a  tool for the expression of a-human sentiment? :kill:

if i was to describe a common daily schedule for the period over which i have been working on these projects, it would be a highly computational one. however even if i was to completely to withdraw, to refuse to acknowledge how much of life is order by the twin processes of networking and computation. i would stil be embedded in a system in which my birt[fn:38]h, sustenance[fn:39],

i wake daily, and usually the first thing i do is check my emails. after that i eat, drink coffee and walk to my studio. there i will usually spend the first two hours reasearching, either reading books on a relevant topic or trying to follow any blog posts or online tutorials about the technical aspects of the 'black boxes' that are the technical building blocks of my projects.

** networked experience

my definition is an embodied process of understanding that takes place across a network. some of the times one might typically include the remote administration of computers, multi-user collaboration on documents (as seen in services like google docs), or even on a  more basic level telecommunications services of all kinds that allow for two way interaction.

here we notice that the technologies that *offer* networked experience as a technology are unlimited, but it is the situations in which it becomes a *practice* which are interestion to me. what defines the practice is the interaction of more than one participant and the aspect of message communication as a tool rather than crafting.

what i am particlarly interested in is mutual real-time meaning making between multiple particpants or kinds of actors.

** inspirations

the inspiriation is taken from serres concept of 'black boxing'. seeing the world in terms of components. taking one and stripping away layers of abstraction in order to understand the processes involved, then returning the 'box' to its position  with newfound understanding.

in my case i am looking at the current state of human relations as i experience them. i am particularly focussed on the 'machinic' qualities and the managemnt of what is commonly thought of as mediation, and common anxieties and concerns with current engagement. i am usingtools that seem applicable and the easiest and most relevant to the concerns. typically the same materials such as, web page scripting, electronic components and sensory inputs and outputs, that are involved in the 'black box'.

so while the work might seem at first technical in nature. i am more interested in trying to 'simply' understand a set of relations and use audio as a descriptive tool.


the four art installations i have assembled represent a set of considerations about how music and technology should interact, and of what this might mean for wider attitudes about the role of the computer in music and society at large.

*** todo
** how we got to

   my research has been into the technologi]cal ideologies that have shaped attitudes to the use of computers in music. particularly the lineage of political strains romantic individualism and utopianism that beacame a part of the ethos of what is know as "the california ideology"[fn:40] this fusion of various strains of thought among academics and inventors after world war two would go on to shape many aspects of the design and research into the use of computers that we continue to use today.[fn:41]

similarly to the cyberneticians, counterculturaliststs and techno-utopians, i wish to explore the interaction of sytems and tools and how the relate.

however in the field of music has at times been both highly influential, as fred turner argues that the use of rock music and stereo equipment as a 'mind expanding' tool was highly influential on the design of the computer.

however the notion of computer music has also offered a challenge for software designers to offer a satisfactory interface for,

it has also at times offered a challenge to the

it is my argument that aspects of thinking about how computers should be used in art and music are limited by ideological constraints on the kinds of interaction that can be permitted.

the lineage of the the 'california ideology' on interaction with computers today seems to enforce the idea of engagement witha  computer being focused on having one operator, holding tight deterministic control over one program utilising an acceptable set of input and output techniques.

however rather than attempting to completely divorce myself from this lineage or propose my own utopia. i wish to make a study of these forces of technoligical ideology and incorperate it into my artworks. by blending representations of the problematic lineage and present state of paranoia with other utopian visions of computing that never quite made it. as well as some of my own ideas about what might be possible in the realm of collaborative experience and new and experimental engagement with machines, others and ourselves. i hope to reintroduce political ideas into the discussion of technology by reintroducing the social and political into the musical and technological landscape.

i argue that there is a link between some aspects of the transhumanism which has influenced much of technological design and desires of transcendence in 20th century music compoers such as john cage that has emphaised transcendce at he expese of 'silencing the social' in the wods of douglas kahn. it is not my wish to decry these works, rather to celebrate and reconsider them in the context of today where we are never sure if we are too connected and being surveilled, or too alone and alienated. instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there.

** todo unexplored futures

** todo future interfacing

i feel that my work is a kind of physical reaserch into the terms of contention and the possibilites they might offer. i feel that difficult, negative or contentious terms are not as exhausted or pre-determined in meaning as we might imagine.

 of one vision of computing with some of the other

as well as considering the ideaologies and politics that have informed the design of our 'tools', the works look at the ideas about appropriate aesthetics


as well as the aesthetics of the msucial landscape that those tools, their operators and composers help create.

it is my conjecture that in followng the history of early computing and developments in musical technolgy, we can see how the culture of three areas in western culture, military industrial and academic, became a key part of what i have termed 'contract culture' in the world after world war two.

the following works are a study in the relationship and possibilities in the spaces between communication technology and artistic practice.

communications technology and musical practice hold much in the way of a common history, converging and

albeit a

 practcie, tradition and aesthetics. from the use of drums as a signalling tool, or even drum languages [fn:42] to the development of brass instruments for

and aesthetics, these works attempt to explore what the future of this relationship might hold.


on a personal level one piece of anecdotal evidence that i have noticed is the large number of programmers and ict (informatin communicatons technolgy) workers that are musicians, composers or disc
jockeys[fn:43].

*** todo look up famous ppl doing both

links between player piano and loom.


*** todo history of ict links to music tech


one of the more interestng developments of the late 20th and early
21st century is the shift in the role of computing. inititially
considered a tool limited to calculations and reckonings [fn:37], the
ability of computer to transmit and record has made it into a highly
effective communications tool. it is the tension between these two
roles, what i have started to think of as a tension between two different models for the organisation of information as outlined by de landa..

of in the heirachy of information organisation and transmission that is deeply explored in

between the signal and database, that i see exemplified in the contempory discourse about
surveilland and technology.[fn:36]

a computer can perform many roles, part of what makes general purpose machines interesting is their ability to be reconfigured. however that is not to say that the possibilities are limitless or easily explored. there are many things that are naturally difficult to do with general purpose computing for a wide variety of reasons that are too long to list. [fn:44] furthermore, the manner in
which a product is designed, developed and organised, is often
specific to the workplace culture, organisation and mode of production
under which it originated. these kind of influences are likely to only
deepen rathr than disappear.[fn:45] a classic text describing this
scenario is the study by x..
*** todo find article about organisation culture i have

many of the functions of modern society depend upon the computer not as a caculator but as a communications tool to relay messages. however in practice, the processes that allow communication to take place, message packaging, routing, encryption, transmittion and error checking are all based on the computation of algorithms. because of the hybrididy of modern communication, both computational and networked, i have chosen to study how modern communication and musical practice can be interrelated.

as this project, determined in looking at 'possibilities', has a somewhat futuristic bent. i have elected to be somewhat wary of the degree to whih i cast the future in the mod eof my own emplacement. this circular inevitablility of conditioning my works into a kind of 'future-present' is somewhat inescapable. however in an attempt to mitigate this i have tried to take inspiriations for my work from other 'failed utopias' as much as the one i currently reside in.

in looking to early expectations and the failed dreams or unexplored possibilities of early omputer history, particulary notions of socialist computing, artificial intellignece, cybernetic surveilland and hippie counterculture, along with the ideas of modernist music composer such as xenakis, berio and stochausen, who all had similar utopian notions about the future of both society and their art.

the cybersyn surveillance project of allende's chile, the cybernetic counterculture of 1960's san franciso and

i have instead looked at other failed utopias. since this work is a study in the effects of networking and computation.

to do so ii have studied

in order to look at some of the possibilities, it is necessary to apporximate

a closer look at the terms involved part forms the basis for beginning this work.

exploring some of their neglected meanings and history of terms and contrasting that with where the emphasis of specific definition lies today is a key part of the work. by looking at the complete history and meaning of terms, particularly alternate meanings, i feel we can begin to excavate other possibilities, possibilities that were always available but feel cut off from now.

for example, the word computer has a been on a historical journey from meaning a human being that makes calculations, to a device facilitation calculation. however even the interesting parts of that statement miss some of the socio-cultural aspects of what a being a computer means.

for instance that computers were once large teams of people used in warfare to calculate distances, supplies and give reckonings for artillery. or that later computers became numerical analysts, a job that was generally gendered to be for women, and teams of women were given the task of managing early machine-based computers. (hmm prob not necessary, incl. refs).

how to portray this rich and often conflicted history in a word is a difficult task. we see that  a key role for the artist can be excavating meaning. looking that the meanings that have been applied over the years and following a common task in critical theory, asking why certain aspects have traditionally been ignore, or taken as a given. because of this, to begin my process i have given in depth listings of the meaning of key terms for the suite of works.  a dictionary definition offer a reflection on the range of meaning and the suggest links to the history of what are seen as ‘modern’ terms. i am seeking to try and combine and undermine these terms to try and understand my own position.

networked, experience, computational, aesthetics and surveillance.

of these five terms the only term not given in the title of the study, ‘surveillance’ represents both the shadow of the other four terms and also what i suspect is the means to analyse and explore the possibilities of the other terms.
*** issues w/ thinking of sound based art-work as 'time based media'
    if installation is not a processional peice, w/ beginning and end, where does that situate sound? digital influence. is adaptive/ generative sound still time based? is it more real time and responsive?


* footnotes

[fn:1] (en)framing heidegger's pilosophy p.8

[fn:2] enframing

[fn:3] heidegger qct

[fn:4] postman, medium is metaphor

[fn:5] heidegger and technology

[fn:6] description of links between software and constructionism

[fn:7] wtf is ontotheology

[fn:8] w concern technolgy

[fn:9] ref to dependdence on human actors in cybersyn

[fn:10] link to uses of term

[fn:11] link to new aesthetic site / files

[fn:12] idea inspired by frocki's first film.

[fn:13] link to weiner

[fn:14] link de landa, berry.

[fn:15] idea taken from the talk,"the web that wasn't" )[[webthatwasnt][twtw]]

[fn:16] link to deetails on javascript streams

[fn:17] article about uses of early phonograph

[fn:18] edina 64

[fn:19] whats a daemon yo.

[fn:20] berry 10

[fn:21] berry 10

[fn:22] softwareised society, link opening of phil of software on dependance on software for survival. berry p.

[fn:23] berry, p. 6.

[fn:24] berry and deleuze, p. 18.

[fn:25] berry p.62

[fn:26] software is eating the

[fn:27] link to treer main history book / topics

[fn:28] stoch to xenakis quote

[fn:29] link five eyes surveillance

[fn:30] def of

[fn:31] link to classic essay about design of saftware informed

[fn:32] any links to this? there was a bit from deland

[fn:33] sousveilance

[fn:34] foucoult link, design of software and oppression

[fn:35] functions in programming.

[fn:36] computers and society

[fn:37] cybernetic revolutionaries

[fn:38] design of medical monitoring machines (see berry)

[fn:39] everything from the control of crops to the management of wild environments and  population control of wild species

[fn:40] link to[[http:hrc.wmin.ac.uk/theory-californianideology.html][barbroo, cameron - hypermedia research centre

[fn:41] examples: skeudomorphic design, interactinon models. give more

[fn:42] ref to drum languages

[fn:43]

[fn:44] here i am thinking about constraints like technical capabilty,
machinic power as well as cultural determinism, usability constraints
or challenges of imagination.

[fn:45] ref to book on the desing of programs reflecting workplace.

[fn:51] define what technicity is

[fn:46] google autocomplete suggestions description link

[fn:47] link between abductive reasoning and ai.

[fn:48] Think python p. 7
