#+TODO: WRITE EDIT REVIEW | DONE DELETE
Computational Ecologies
Reification and second order materiality

* Parasite Suite - Exploring social-computing and art.

* WRITE Abstract

* EDIT Introduction
** REVIEW Quotes

 These articles are valuable; it is important both to observe how particular technologies function in the world and to point out possible new directions for these technologies. However, a significant dimension of technology goes unnoticed by most commentators: the way of thinking that lies behind the creation and use of technology. If more commentators on technology were able to wade through ‘The Question Concerning Technology’, as well as some of Heidegger’s other writings, they might discover some exciting new pathways for their thinking. [fn:1]

The great breakthrough of ‘The Question Concerning Technology’ is that it shifts the focus away from specific technologies and toward the modes of thinking that lie behind these technologies. However, within this breakthrough lies a danger: it is possible to focus on the thinking behind the technology to such an extent that meaningful distinctions in the world are obscured. In a remark that was originally a part of ‘The Question Concerning Technology’, but was later excised (Harries, 1994, p. 233), this danger manifests itself:

   We know very little about the ways in which software is socially created, the nature of software itself; how discourse, practices, and knowledge get translated into algorithms and code; the geographies and political economy of software development; how software is embedded into various social systems; how software applications work with each other to create complex assemblages that work within and across scales; the power wielded through software's "secondary agency"; and how software alternativly modulates the production production of space and transforms the nature of governance.[fn:2]

   There is evidence that people naturally respond to computers as if they were people. When they work well, we think of them as teammates, and when they are obstinate or rude, we respond to them the same way we respond to rude, obstinate people (Reeves and Nass, The Media Equation: How People Treat Computers, Television, and New Media Like Real People and Places). [fn:3]

   /According to Heidegger, technology is distinct from what we do with tools, instruments, equipment, or the way of thinking about those things. Likewise, modern technology is not reducible to technological artifacts, devices, or the techniques that produce those things... modern technology in essence is Heidegger’s designation for the way in which things give themselves in and through an epoch. Technology, or what also can be referred to as “technicity,” concerns itself with the ontological way in which things reveal themselves via a “sending”/

/We don’t know what these bits represent, they could be an integer, a float, they could be noted in little endian, big endian, they could be some letter in some encoding, they could be a pixel RGB, RGBA, grayscale, whatever. They could be an audio sample, signed or unsigned. They could be a processor instruction that actually tells the CPU to do something. And these roles can be assigned arbitrarily. Each data point needs additional data about itself, stored somewhere else, describing what is supposed to happen with this data. Then, depending on how the machine operates on these bits, they move towards different meanings. This is why I think it is productive to say: Everything inside the computer is a performance./ [fn:4]
** REVIEW Introduction

  Computers can become a tool to describe embedded values that we often do not take time to take notice of. Computers can draw new, arbitrary relations. Theory as interrogation of computational method.

  'Parasite Suite' is a collection of works describing the pssobilities for social-computing as artistic medium. Social computing is a concept describing the collaborative aspects of online behavior, it seems to be an important concept in economics, computer science and information systems.[fn:5] In general it describes scenarios where information is created and distributed across social collectiviies via computer mediated communication [fn:6]. One of the important qualities specific to social computing is that it is not anonymous, details are linked to people in a significant manner. However I wish to show that all comuting is social when we consider the wider world of computation use and explore its theories and values. As such the project aims to consider the social relationahip between technology and sound art.

An important quality of social-computing is that the information is that it is indexed against the user, reused, accumulated, and often sold. This allows data to accrue value and descriptive use beyond the present moment. An importnant quality to the information is that it is always 'linked' to an identity, and that the accumulation and dissemination of this information unfolds in time.[fn:7]

 To portray this relationship I wish to explore the phenomenological and aesthetic aspects of social-computing using sonically focused art works. The project documents legitimate concerns about social-computing while exploring these systems that produce both awe and anxety. By using social scenarios mediated by computation, the project aims to consider the materiality of computational abstractions, as well their attendant power heirachies. The works use the gallery as a setting for common social-computing techniques, such as data-logging, metadata extraction, computer vision and algorithmic surveillance, these social maipulations hope to provoke consideration of the historical use and influences behind many computation techniques. I am sugesting that there are many unexplored or neglected possibilities within computation due to cultural bias and lack of reflexivity about the medium.

 I argue we need to recognise that technology has two ways it affects our experiences. It encourages orderings based on its own metaphors (particularly its modes of information transfer), and it encourages  appreciation of the world based on its own systems of recognition and reasoning. These two systems, which I term 'Networked Experience' and 'Digital Aeshetics', are inescapable aspects of the instrumental use of these technologies. However their social and cultural limitations need to be recognised and expanded upon if we are to have any hope of ameliorating the 'false promises of the digital revolution' and develop the more radical potentials of these tools. My small gesture is to reifiy the social manipulations that machines can introduce, and employ them beyond common scenarios. Following Heideggerian theory, I belive that a fuller study of the humanistic aspects of social-computing contains the aspects of its own reconsideration. It is hoped that I can use social-computing as a productive concept to explore and critique the contour of the political and economic aspects of modern computing.

   Parasite Suite takes common anxieties about the proliferation of these  technological systems as a starting point, particularly concerns about the use of institutional surveillance, now much of the sublimity and amazement of networked computing has worn off. References for the works include critical theories of the digital,[fn:8] as well as works by composers and artists with an interest in the relationship between technology and society, such as..., Iannis Xenakis, Włodzimierz Kotoński, Zygmunt Krauze and Holly Herndon =Add to this?=. I believe that there are phenomenological and aesthetic aspects of social-compuation that tend to be self-reinforcening, deepening the values that precipitated their own development, to the exlusion of other possibilities. This I term a kind of 'parasitism', where technology invites itself as a conceptual participant in all kinds of social negotiations. I argue we need to recognise that technology encourages relationships with the world based on its own metaphors (particularly its modes of information transfer), encouraging thought and engagement based on its own systems of recognition and reasoning. Appreciating this parasitic reltionship with technology, as both hindrance and tool, is the first step in developing new relationships with technology.

   The project is realised as a set of four works that explore social-computing: an installation, an interactive tool, a musical piece, and a website. The works consider humans how humans have to contend with a 'computational' theory of being, a term introduced by David Berry in his book /Critical Theory and the Digital/.[fn:9]. It is a neologism describing a ontotheology (theory of being) derived from the metaphors of the present computing context, which Berry argues are networking and software design[fn:10].  In compuationality, the metaphors of computer usage, (such as the terminology of databases, programming paradigms, data transfer mechanisms and hardware design) develop serious influence over our attitudes to other entities, hindering possibilities for alternate paths of development. The present computing climate, which for Berry is defined by the tropes of networking and the logic of pattern recognition, begins to predominate relationships with the world. The concept is largely and elaboration to the concept of 'enframing' developed by Martin Heidegger in "The Question Concerning Technology".[fn:11]
   =Give Examples=

The text is a difficlult read at times and occasionally arbitrary in its allocation of concepts and pronouncements (particularly the value of /releasement/) However, W notes that, /The great breakthrough of ‘The Question Concerning Technology’ is that it shifts the focus away from specific technologies and toward the modes of thinking that lie behind these technologies/ However, Heidegger also  noted that /it is possible to focus on the thinking behind the technology to such an extent that meaningful distinctions in the world are obscured./ A remark that was originally a part of ‘The Question Concerning Technology’, but was later excised (Harries, 1994, p. 233)(w)

Enframing is Heidegger's term for the essence of modern technology. The term describes a danger within modern technologies method for the revealing of truth. In Heidegger's theory, modern technologies reveal truth as a reserve of energy, as technological potential, in tune with the technical paradigms and values of the time (named in Heidegger's terms as 'standing reserve'). We can do nothing about the arrangement of enframing or its influence, it is part to the technology, we can only consider how we will respond to it.[fn:12] =Examples?= Heidegger contrasts this with traditional craftwork... Heidegger doesn't feel that this should necessarily put us off the use of technology, or define it as a bad thing, it is rather need to adopt an attitude of 'releasement' (the ability to have a deferential attitude, or apathy, towards the necessity of a technology), that he finds most important.

The mechanics of enframing are dependant on two kinds of concealment of a mediating presence. The first is the abstraction of machinic process that allows the technology to be used or capitalise on other technologies, this is often seen in music composition and software design where we abstract complexity or use a software library to focus on a new or previously unreachable area. There is then a second kind of concealment, which Heidegger describes as 'concealment of the concealment'[fn:13], it is the taking for granted of a technological abstraction or tool. The first abstraction is treated as a given, or as its own kind of truth, to the point of immateriality, such that the technological underpinnings and social epoch are ignored or treated as natural. This second act of concealment is regarded as more insidious, unique to modern technology, and most importantly able to be repudated thorugh awareness.

    In this sense we  are reminded of our symbiotic, yet parasitic relationship with technology; we see it as a way to advance understanding, and yet doing so dominates our experience and potential. As one of the goals of software is to be to acheive a simulacrum of 'realness' of the process it is imitating to the point of being indistinguishable, though the use of design or organisation choices.[fn:14] Eventually a sucessful technology can 'dissappear', becoming an unacknowledged part of all experience, this is particularly the case with immitative and surveillant techniques of computation, and it is these I wish to focus on returning to appreciable froms of representation for this project, throught the use of audio visual manipulations based around the notion of exploring parasitic relations.

    Berry writes that Heidegger's notion of enframing choses electricity and modern-physics as its two technology metaphors to show as examples.

 Berry's notion of 'computationality', is correspondingly based on metaphors from networking and software-engineering.

 It appears to me that the concept is also similar to Michel Serres notion of 'back-boxing' and sociological studies in social constructionism.
The resulting symptom of enframing is an orientation towards the world tht is inspired by characterstics of the technological metaphor that the abstraction describes. In Heideggers's time he labels this 'challenging forth', an expectation for nature to reveal itself as a kind of 'standing reserve', like a reseviour of electrical potential awatign connection to a circuit.

 There seem to be two dominant metaphors within software-engineering and networking that have emerged of late; the idea of 'the stream', starting with data and transferring itself into both consciousness and life-force, and the rationality of the 'new aesthetic', a logic of distinction and pattern recogniton.

 These two systems, which I term 'Networked Experience' and 'Digital Aeshetics', are inescapable aspects of the instrumental use of these technologies. However their social and cultural limitations need to be recognised and expanded upon if we are to have any hope of ameliorating the 'false promises of the digital revolution', and develop the more radical potentials of these tools. My small gesture is to reifiy the social manipulations that machines can introduce, and employ them beyond common scenarios. It is hoped that I can use social-computing as a productive concept to explore and critique the contour of the political and economic aspects of modern computing.

** EDIT Networked Experience - Internet Phenomenology?

   It is a kind of group consciousness based on the ethics and values of the companies that provovide the infrastructure, develop the technology and program the softwware that allows this to take place.[fn:15] It is as if we always see thng through others eyes, and in the case of networked experience, it is the eyes of the technologist.


   'Networked-Experience' is my term for the phenomenological experience of 'computationality', a sensory world where algorithmic processing and connectivity are taken as expected facilitators of experience. Here sensory experience expands beyond just an interaction with computers into a 'revealing' of the natural world as a networked set of streams able to be connected and manipulated at will. This kind of experience is flawed on many levels, it ignores...

   To me it is a kind of utooopian fantasy of a ever at hand present, where one proceeds through events on ly reacting to the immediate moment of what is happening as an reactive, embodied mind.

an important aspect to note is that this 'computational' mode of experience isn't dependant on any kind of technology or state of development in itself. as i have found in my research it is possible to create a networked experience based on streaming data and reactions based almost entirely on inter-human communication, as was the acase with the cyber-syn project in 1970s chile[fn:16].

   However rather than explicitly rejecting it (which I feel is impossible) I'm more interested in what open to social manipulation when this kind of thinking is in use. The easiest way to decide what elements to focus on are to look at the concealments that a technology makes. Firstly I think that accumulation and memory are the first to be ignored in this attitude, as are th material aspects

The best tools I think to draw out the grain of networked experience, are to firstly create one, and then draw up on history and logs. Much as the providers of services such as facebook and twitter do


 Because of this the experience of real-time networking often makes information seem like a vector (or stream ) with a velocity and direction, and one that can be acessed by turning on a tap and directing the flow. The metaphor of 'streaming-forth', thus makes other objects, seem like processors of real time streams of information. Already this can be seen in changing paradigms in computer programming [fn:17], that emphasise the metaphor of piping, whereby modules are connected to trasfer an awaited stream of information. It is as mucha  response to the challenges of dealing with a new paradisgm for the delivery of information s a application of a metaphor that was already in peoples minds.

 David Berrys's term for this type of experience is 'streaming-forth', as the network  becomes the characteristic mode-of-revealing of nature. 'Streaming-forth' is an expectaton for entities to reveal themselves in terms derived from meatphors about computation.


A mode of revealing is the method by which technologies transform, store and distribute the resources that nature has to offer.'[fn:18]


 Primarily those of networked 'streaming', in which the relationship with an object is derived from the ability to make a connection and establish a process to deal with its 'stream' of data. This kind of thinking especially ignore the material factors of production...
it's sense of time is decidedly 'now'...
 alogrithmic processing is made to seem  transparent, direct, and natural, as if a staggering logistical effort isn't taking place every time I make a google search.
This sense of effortless computation is often acieved by careful user-interface choices.


 This leads to famous phrases that seem typical of the present such as "all you need is data" [fn:19]. However these data streams also have trajectories, and sources, controlled by physical infrastructure and logistics, controlled by powerful entities. Like a water company. Perhaps the best example of the manner in which streaming-beings, as the model for humans to act as is seen is in the expectatons placed on workers in labour relations. Likewise people also begin to see themseles in terms of being 'streaming-beings', both in terms of producing a multitude of real-time information based on behavior (often used for surveillance and interaction studies). Also we are seen as responding in real time to demands placed on us, as seen in 'zero-hour contracts' that call for workers to dynamically respond to changing work hours (rather than beng called upon as with previous contract based systems)

 The experience of considering oneself both a recipient and generator of the 'stream', is one of the defining characterstics of modern experience. If participants are indeed ordering their world in response to 'streams,' then typical goals include processing information, performing algorithmic transformations, and searching for ways to filter information to make it /computeable/, which leads into to our second quality of computationality, recognising patterns through abductive reasoning.

*************** Identities as 'Streaming Beings'
*************** END

   What I am particlarly interested in is mutual real-time meaning making between multiple particpants or kinds of actors.

** EDIT Digital Aesthetics - Computational Ontology

   Computational ontology - ordering of the based on distinction / abductive reasoning

Also described as process of 'distinction' by Galloway in 'Against the digital'.

Similarly to neeetworked experience, computational aesthetics were able to be seen well before the advent of personal computers, it is only now that they are ubiquitios and hard to notice however, as with a 'good' photoshop touchup.

   In contrast to the sensory aspects of networked experience, digital aesthetics are the consecuences of the epistemology of computationality. At present, digital aesthetics are often describes under the bunner of 'pattern aesthetics'[fn:20], of 'the new aesthetic'[fn:21], as they represent a kind of rupture of the virtual and its logics into the real world. =Give Examples= However I wish to argue that this kind of knowledge system that machines are introducing has always been in existence, despite its renewed prominance =Give Examples=. the key aspect of digital aesthetics is idnetified by Berry as having 'abductive reasoning' as its logical modus operandi.

Example
"Under capitalism, cosnnsciousness is shaped and moulded within the frame of identity framing, that is, 'the subsumtion of all particular objects under general definitions and/or unitary systems of concepts" (Held 1997: 202)

 As a result, the particular is usually disllved into the universal. Today the unitary systems of concepts is supplied by comuputation, and more specifically by the computational categories and total system of computationality, which is increasingly manifested in a meiated 'new' supplied by real time streams.

While networked experience determines our mode of identification and engagement, I beleive that it is computational 'patterning', that has been adopted as our paradigm of what an experience should 'feel' like. It is a paradigm, goal and aesthetic system based on the implementation of the best pattern recognition system currently available to us, abductive reasoning.

 Abductive reasoning is a an approach to reasoning, ubiquitous in its use in software engineering. It is most often used when trying to make judgements working with 'fuzzy' or flawed data sets and can be contrasted with deductive (logic, proof-based) and inductive (probable, evidence based) reasoning. It is the 'fuzziest' kind of reasoning, somewhat akin to a 'best guess'. Abductive reasoning attempts to guess based on the information at hand, refining the set of best guesses as the quality improves or amount of data accumulates. one of the most well known examples included predictive text, other more complex examples have been shown by the google corperation, such as autocomplete suggestions[fn:22], early work on abductive resoning in computers was highly focussed on artificial intelligence[fn:23].

*************** abductive reasoning in real life...
		Similarities with symptom recognition in medicine. Influence of /A Pattern Language/
*************** end
  These two systems, which I term 'Networked Experience' and 'Digital Aeshetics', are inescapable aspects of the instrumental use of these technologies. However their social and cultural limitations need to be recognised and expanded upon if we are to have any hope of ameliorating the 'false promises of the digital revolution', and develop  the more radical potentials of these tools. My small gesture is to reifiy the social manipulations that machines can introduce, and employ them beyond common scenarios. It is hoped that I can use social-computing as a productive concept to explore and critique the contour of the political and economic aspects of modern computing.


/this frantic disorientation uderneath the surface is therefor insulated from the user, who is provided with an interactional surface that can be familiar, skeudomorphic, representational, metonymic, flat, figurative or extremely simplistic and domestic./



Computationality is a form of communication, it only possible to acheive packet based communication through abductive reasoning and networked metaphors. Computation also allows for new combinations of public/private crossover.

   " computers classify according to the patterns which have already been prorammed within them . thus patterns serve to create a language, a /pattern language/, which is a set of classificatory means fo the identification of the type of thing an object presentented to the computer is. not the particular object, but the abstract calass of teh object and there fore the abstract pproperties and understandings that are pre-coded intot he computer and provide the bass of comprehension".

 The resulting experience can be described as a 'pattern language'. A 'pattern language' is something that we can be aware of, but whose methods tries to make itself 'transparent' to us. this appeal to transparency goes beyond the user interface level into all manner of abstractions at all levels of coded space: interfaces, application programming interfaces(apis), objects, macros, function composition, integrated circuits, all exist as abstractions that can make an processes result seem more natural when they hide away complexity. these toos are crucial for managing all of my projects, however the cumulative effect of these tools, often appears as a kind of 'magic' to the person using the tool to prepare an experience, and as a kind of faux 'natural' to the end user, who is intended to be none the wiser.
*************** pattern example
#+begin_src javascript
// sensor inputs, mouse cursor postition, page location,

#+end_src
*************** end

   for example, if i was to write a program that could recognise a pattern, say that you were reading this paragraph. i would first have to consier /how/ you were reading the text, both the phsysical device and medium. for instance in a book, on  a tablet or mobile device or on a computer
 in preparing to construct the algorithm i would consider what sensory inputs i have available, then design a solution
 and intention to read the paragraph that you are currently reading. a program might consist of a tracking of the

*************** personal example of emplacement
*************** end


'computationality' can then be experienced as a combination of computer processing and networking capabilty that embody a particular aesthetic and mode of experience for those that interact with the works [fn:24]. the particulars of the experience and aesthetic of 'computationality' has been specifically collected and outlined by others[fn:25] but i loosely define it as the experiencne of a real world decision that seems influenced or larely determined by by what would be appropriate for the algorithmic sensibilities of a machine rather than a human sense of design aesthetic. the manner in which this is realised

     a particular aspect of the 'computational' i have focussed on is the felt sense that a machine can be treated as a participant and social actor rather than a tool.

*** edit
  an ontological shift towards sympathy for the machnines 'algorithmic' methods of understanding, mediating our own notions of beauty. the projects are intended to be open ended, generative and participatory, blurring lines between artist and audience. a key goal of the works is for proamming choices to affect dramatic shifts in  social roles and duties for participants. the concept is to place emphasis on the notion that a generalised  machine can constructed equally be a machine gun or a vacuum cleaner, or a collaborator or spy. despite the outward presentation of a work or adoption of controversial digital 'features' such as data mining or monitoring,  technological systems are much more than hardware and code, they represent a,"'seamless web' of social, institutional and technological relationships.'"(122)it is the the heirachies and logistics of society that  play a crucial role in determining the material formation of a work[fn:26].

    the conceptual inspiration for these works is drawn from histories of early computing, the philosophical influence of early digital design, and cybernetic thought [fn:27], as well as philosophical works about technology and communication. [fn:28] specific models and refereences for the works are outlined later in their descriptions and documentation. in general, it is the history of cultural metaphors about computation, as well as studies of  technological opportunities that never materialised or fell to the wayside, that have helped me to explore other possibilieties for social interaction in computing.[fn:29] by exploring these topics we can see interesting possibilities for restructuring networked engagements with machines. i wish to argue, as has been shown by eden medina in her study of some of the rudimentary techniques explored by the cyberneticians of the cybersyn project in allende's chile, that it is not realtime communication of high tech computing that determines the sense of a 'networked experience', rather it is the idea of bi-directional streams of information that are being responded to. this idea is central in much of cybernetic organisational theory, and informs a wide range of practices today. one which i use extensively is the 'streams' programming technique, one that is prevalent in an extensive number of web programs at the moments.[fn:30]

*************** write go on more about audio
 in particular i have focused on the act of surveillance, a term that i am trying to explore beyond of its pejorative sense. exploring the  term surveillance has allowed me to consider the thin line between social engagement and intelligence collection. particularly when considering the perspective of a machine, it can be difficult to differentiate between methods that might enable new kinds of engagement and those that might alienate. in parasite one i have tried to design a surveilance model that offers two-way methods of remote listening by exploitng aspects of audio
*************** end

this term surveilance represents a useful union point between the machine and network, and implies a model of engagement based up monitoring and responding to interactions in a dynamic manner. for my studies it has come to represent a point of coalescence between the anxieties of today and an area of early study in the field of cybernetics. particularly in the early era of computing, and similar to speculation about the possible uses of the phonograph[fn:31], cyberneticians were wildly imagining what a computer would be useful for. certain unexpected innovations such as email also totally changed the field.

"e-mail emerged in 1971 when users began experimenting with ways of sending electronic messages from one networked computer to another. in her study of the internet's origins, janet abbate writes that e-mail "remade" the arpanet system and caused it to be see 'not as a computer system but rather as a communication sytem.'(ref.82) 1.[fn:32]

it is my belief that the notion of the usefulness for the computer in exploring musical, social and political possibilities can often be surprisingly limited. the key area of limitation i wish to explore is in the area of networked interaction between multiple agents. the key theme is essentially how the 'social' can be introduced into artistic and compositional practice.

the notion of the responsive surveillant, who may take on any biological or material form, is one of the cornerstone ideas of the field of cybernetics. we can see this biologically influenced notion otherwise known as a feedback system everywhere from the thermostat to many of the software 'daemons' of computers that operate in the backhand of unix based computers.[fn:33]

in these early experiments with the idea of 'what a compute should be', we can see the possibilities and disappointments of concepts such as like 'socialist computing', and efforts to radically reconsider the function of the computer when it is relevant to the culture and philosophy of disparate groups.

artistically a reconsideration of the manner in which we interact with computers and each other under the banner of surveillance also represents a sincere attempt to portray some of the radical possibilities of computer art when it embraces its lineage and explores the anxieties of the present.

these three areas: the philosophies of how machinic interactions have coalesced into one commonly accepted into a common form, a look at unexplored possibilities and under-emphasised potentials in the present, and a search for how to revive those alternative futures, each represent the three strands of artistic research in the project.

i have attempted to unify these into four project.

it is a kind of consideration of the discrete and quantifiable that happens when we begin to employ a kind of empathy toward a machinic perspective.
*** edit
**** p1.
'immateriality of software[fn:34]'
describes it as a /super-medium/ that unifies other forms,  (tv/film/radio/print), rather than containing them it reforms and reshapes them into a "new unitary form"[fn:35] "this super-medium acts as both a mediatingn and structuring frame that we must understand through its instantiation under particular physical constraints" - rejecting the immateriality of software. analysisng the doing, platform studies.

the terms 'softwarized society' coined by dacid berry [fn:36] encapsulates what i see as the outcome of networked experience and computational aesthetics. the term describes the impuct of computers on culture as both metaphor and (an often transparent) medium. {such as?} as technology inculcates itself we are indanger of forgetting how entangled with computer code we really are, it would be hard for me to think of any aspect of my daily life that isn't entangled within the world of software code, living within a nation dependant on software, and using it to write this exegesis. software is part of the narrative of our lives, and yet often overlooked. fuller (2006) notes, "in a sense, all intellecual work is now 'software study', in that the software provides its media and its context..." berry encourages us to think about the "structure of feeling[fn:37]"  and methods of usefulness permitted by code. noting that technology is a cultural metaphor as well as lexical and physical object. these varied cultural thoughts about technology in relation to the self and society inform practice and engagement with tools as well as wider social and economic relations. to the extent that berry believes the metaphors of software in particular, to form a 'plane of immanance' that shapes relations[fn:38].
*** write

by treating projects as socio-technical assemblages, connected to "broader networks of social relations and institutional ensembles"[fn:39]. i plan to
use technology as its own medium to consider the role of technologies. the intent is not to reject or provocate but to describe origins of human anxiety about the digitization of our world [fn:40].

as the context of the work is on social uses of technology, particul the manner in which  actors roles this can be manipulated within these, research for this project has involved histories of the social in computing. within these histories, didactic and utopian attitudes to technology are rife, particularly in studying the histories of cybernetics, early personal-computing and 'socialist'-computing [fn:41].

however they it has tended to become apparent that the hopes and dreams of people like stafford beer and stewart brand are products of their of their time, in which the possibilities of new tools empowering users to create new worlds did seem real. this utopian bent make for interesting parellels with modern composers such as stochasen and xenakis, who exhibited similar attitudes about technology [fn:42].

it is this tension between the utopian attitudes of the past and some of the anxieites of the present. all of which belie the use of the same kinds of tchnology, which i wish to explore in these workds. my hypothesis is that there is a way through this, that within some of the most pervasively distressing manipulations of technology by governmet agencies and coverty actors[fn:43], there are techniques to reconsider the uses of technology once again if we look to some of these abandoned histories of computing.

*************** write para on theory
*************** end

with the hope to point out some of the heirachies and possbilities bestowed on different actors given certain combinations. the emphasis is on the social and collaborative aspects that are possbile, with their attendant possibilities for exploitation, re-working and misuse both creative and destructive.

one particuular kind of technological assemblage that is commonly known to provoke feelings of anxiety about the digital, is techniques of surveillance[fn:44]  , can have their heirachies and processes changed to give power to new actors and outcomes.

these projects, which try to take the same materials and processes of the anxiety inducing technologies in question are somewhat foregone in their conclusion that is often the heightened ability of established heirachies and actors to utilise these tools for ill will rather than the technic itself.

in my attempt to consider the design and implementation of tools like computer vision, real-time communication and data-colleciton, i have often found that the design and user experience as a developer is often imprinted with the culture and expectations of the teams that assembled the foundations of these tools[fn:45]. in a sense i have discovered  a source for my own anxiety in a consciousness of the kind of corporate cultures values embedded in the design of systems. my response to this has been to try and configure atypical user interfaces and methods of engagement, such as avoiding teh user metaphor of a person sitting at a computer terminal with keyboard and mouse, and trying to treat sound as a first-class user interaction medium[fn:46].


in this sense the work is inspired by coucpets such as 'sousveillance'[fn:47] where a technology is leveled against an oppressor rather than the opposite. in my course of exploring how to 'turn the tables' however, i have also found that it is often the composition of technologies and the relationships that their design encourages[fn:48], that require the formulation of organic and locally specific technologies that offer solutions more relevant in my case for an artistically inpired, more affecting outcome, and on a general level benefit participants.

*** todo quote about subroutines and influence on programming[fn:49].


however the process by which i developed this project was not from a carefully chosen theme, but rather a methodoology where i have sought to describe some of the 'back boxes' of communications that i interact with on a daily basis. my methodology for investigating something like data-collection, monitoring and signal intelligence is derived from creating a project that mimics a small subset of these behaviors in an uncommon context, and then noting the processes that are fundamental to the existence of the 'machine'. this method involves treating the world in a manner very simlar to the concept of a 'function', otherwise known as a subroutine in computer programming. in some way i am attempting to import concepts from a pradigm in computer programming, 'functional programming'

many interesting things can be said about

. it just so happens that when i consider some of the inherant qualities of the manner in which i would conduct myself, even in moments that i step away from a 'screen', the encounters of my life are all deeply network driven. one of the discoveries of early computing i sthat computational speed makes vastly wider and new kinds of networks possible.[fn:50]
pattern aesthetic-


|--------------------+-----------------------------+---------------------------|
|                    | technicity                  | computationality          |
|                    | (modern technology)         | (postmodern technology)   |
|--------------------+-----------------------------+---------------------------|
| mode of revealing  | challenging-forth (gestell) | streaming-forth           |
|--------------------+-----------------------------+---------------------------|
| paradigmatic       | technical devices,          | computational devices     |
| equipment          | machines                    | computers, processors.    |
|--------------------+-----------------------------+---------------------------|
| goals (projects)   | 1. unlocking                | 1. trajectories           |
|                    | transforming                | processng info            |
|                    | storing                     | algorithmic trans         |
|                    | distributing                | (aggregation, reduction   |
|                    | switching about             | calculation) as           |
|                    | standing reseve             | /data reserve/            |
|                    | 2.efficiency                | 2. computability          |
|--------------------+-----------------------------+---------------------------|
| identities (roles) | ordered beings              | streaming beings          |
|--------------------+-----------------------------+---------------------------|
| paradigmatic       | *engineer* time motion      | *design* info theory      |
| epistem            | studies, method-time        | graph theory              |
|                    | measurement (mtm)           | data viz                  |
|                    | instrument rationality      | communicative rationality |
|--------------------+-----------------------------+---------------------------|

** EDIT Inspirations

The inspiriation is taken from serres concept of 'black boxing'. seeing the world in terms of components. taking one and stripping away layers of abstraction in order to understand the processes involved, then returning the 'box' to its position  with newfound understanding.

In my case i am looking at the current state of human relations as i experience them. i am particularly focussed on the 'machinic' qualities and the managemnt of what is commonly thought of as mediation, and common anxieties and concerns with current engagement. i am usingtools that seem applicable and the easiest and most relevant to the concerns. typically the same materials such as, web page scripting, electronic components and sensory inputs and outputs, that are involved in the 'black box'.

So while the work might seem at first technical in nature. i am more interested in trying to 'simply' understand a set of relations and use audio as a descriptive tool.

The four art installations i have assembled represent a set of considerations about how music and technology should interact, and of what this might mean for wider attitudes about the role of the computer in music and society at large.

** EDIT Historical Studies

similarly to the cyberneticians, counterculturaliststs and techno-utopians, i wish to explore the interaction of sytems and tools and how the relate.
it has also at times offered a challenge to the

it is my argument that aspects of thinking about how computers should be used in art and music are limited by ideological constraints on the kinds of interaction that can be permitted.

the lineage of the the 'california ideology' on interaction with computers today seems to enforce the idea of engagement witha  computer being focused on having one operator, holding tight deterministic control over one program utilising an acceptable set of input and output techniques.

however rather than attempting to completely divorce myself from this lineage or propose my own utopia. i wish to make a study of these forces of technoligical ideology and incorperate it into my artworks. by blending representations of the problematic lineage and present state of paranoia with other utopian visions of computing that never quite made it. as well as some of my own ideas about what might be possible in the realm of collaborative experience and new and experimental engagement with machines, others and ourselves. i hope to reintroduce political ideas into the discussion of technology by reintroducing the social and political into the musical and technological landscape.

i argue that there is a link between some aspects of the transhumanism which has influenced much of technological design and desires of transcendence in 20th century music compoers such as john cage that has emphaised transcendce at he expese of 'silencing the social' in the wods of douglas kahn. it is not my wish to decry these works, rather to celebrate and reconsider them in the context of today where we are never sure if we are too connected and being surveilled, or too alone and alienated. instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there instead by seeking o re-empahises teh socaial, collaboratvie aspects of that is already there.


as this project, determined in looking at 'possibilities', has a somewhat futuristic bent. i have elected to be somewhat wary of the degree to whih i cast the future in the mod eof my own emplacement. this circular inevitablility of conditioning my works into a kind of 'future-present' is somewhat inescapable. however in an attempt to mitigate this i have tried to take inspiriations for my work from other 'failed utopias' as much as the one i currently reside in.

in looking to early expectations and the failed dreams or unexplored possibilities of early omputer history, particulary notions of socialist computing, artificial intellignece, cybernetic surveilland and hippie counterculture, along with the ideas of modernist music composer such as xenakis, berio and stochausen, who all had similar utopian notions about the future of both society and their art.

the cybersyn surveillance project of allende's chile, the cybernetic counterculture of 1960's san franciso and

i have instead looked at other failed utopias. since this work is a study in the effects of networking and computation.

exploring some of their neglected meanings and history of terms and contrasting that with where the emphasis of specific definition lies today is a key part of the work. by looking at the complete history and meaning of terms, particularly alternate meanings, i feel we can begin to excavate other possibilities, possibilities that were always available but feel cut off from now.

for example, the word computer has a been on a historical journey from meaning a human being that makes calculations, to a device facilitation calculation. however even the interesting parts of that statement miss some of the socio-cultural aspects of what a being a computer means.

for instance that computers were once large teams of people used in warfare to calculate distances, supplies and give reckonings for artillery. or that later computers became numerical analysts, a job that was generally gendered to be for women, and teams of women were given the task of managing early machine-based computers. (hmm prob not necessary, incl. refs).

how to portray this rich and often conflicted history in a word is a difficult task. we see that  a key role for the artist can be excavating meaning. looking that the meanings that have been applied over the years and following a common task in critical theory, asking why certain aspects have traditionally been ignore, or taken as a given. because of this, to begin my process i have given in depth listings of the meaning of key terms for the suite of works.  a dictionary definition offer a reflection on the range of meaning and the suggest links to the history of what are seen as ‘modern’ terms. i am seeking to try and combine and undermine these terms to try and understand my own position.

** 'Streaming-forth' and Time based Art
    if installation is not a processional peice, w/ beginning and end, where does that situate sound? digital influence. is adaptive/ generative sound still time based? is it more real time and responsive?


* WRITE Parasite One
** Summary - Inspiration for Work.

The work is focussed around exploring the idiosyncrasies of networked real time communication in the context of a sound art tradition.

The principal sources of inspiration are a re-interpretation of John Cage’s Imaginary Landscape Number 5 (link). My re-imagined take on the work is also inspired by the oblique networking system of the video game Dark Souls (link appendix), as well as the ‘giant’ piano featured in toy store sequences from the movies Big(link) and Lethal Weapon(link).

The initial version of this installation takes place on a staircase with eight stairs. Each stair has a simple floor trigger underneath and adjacent light source to light up a user's feet when they activate a stair.

Each time the program is run that controls the stairs is initialised the stairs are given a sample to continuously loop from a randomly chosen collection of audio files on the installation computer (link to script for sample picker) to act as its streams.
Under the staircase is a speaker playing eight pre-arranged ‘streams’ of sampled information, the volume of each stream, corresponding to stair, is controlled by the floor triggers.

There is also a website for the installation where users can log on to observe and listen to the installation. Access to the website also offers users two pieces of added functionality. After allowing access to users microphone and camera, they can now trigger staircase responses remotely by hovering over a box representing each stream. However by participating in this manner the user becomes part of the installation, the sounds of their microphone stream replace those of one of the stairs in the installation for as long as they are visiting the site.

Realisations
(Video)

Implications

The work attempts to deal with some of the major themes of the collection of works. Namely by looking at surveillance and the idea of ‘engagement’ with the surveyor. The work attempts to press the

Experience

The observed experience is markedly different for the two kinds of participants in the installation as they assume different roles, In-situ visitors are usually at first surprised by the manner of the

** Technical Outline
*** Intro
The installation parasite is a work that occupies a staircase, using 8 floor panel sensors constructed from conductive material and plastic to form large ‘buttons’. These ‘buttons’ are placed under pieces of carpet and wired to an arduino microcontroller communicating with a small desktop computer.

The computer is set to transmit sound within the space using the audio capabilities of html5’s javascript application programming interfaces (APIs) and the microcontroller messaging and web serving capabilities of the node.js server side javascript language.

What is immediately obvious to the participant is that the computer is set to send messages to turn on 12 volt LED strips attached above the stairs, these light up as participants stand on the floor sensors. The computer is also outputting 8 muted streams of audio, a corresponding stream also having its volume increased also when a user stand upon a floor sensor. A the top stairs visible to those ascending there is a handwritten universal resource locator (URL)
directing those who are interested to visit a web page (currently: www.parasite.ngrok.com
(diagram of installation)

all source code available at https://github.com/brookemitchell/parasiteChat

*** Physical Computing - Arduino Circuit

In the spirit of ongoing development, the circuit constructed is simple enough to understand and designed to emphasise direct user input with highly responsive feedback prioritised above consistency of user experience. Sensors are expected to  register input instantly, resulting in the ability for the user to trigger results multiple times simultaneously by adjusting the weighting of their feet or coerce buttons into a ‘stuck’ state by carefully removing weight off the floor panel. These kinds of user ‘hacks’ and edge cases are encouraged as part of the art work rather than erased by attempts to enforce  total consistency of user interaction.

(img – circuit diagram)

The floor sensors that serve as basic buttons are connected to eight digital inputs on the arduino, using the internal pins of each pin to serve as pull up resistors and create a typical ‘button’ input circuit. To control the lighting eight digital outputs send 5v control voltage signals to eight N-Channel MOSFETs (link). The MOSFET transistors have 12v voltage provided by a separate power rail that is gated by the MOSFET, as controlled from the arduino, a  a corresponding LED strip can be illuminated whenever 5v control voltage is sent from one of the digital out pins.

The firmware of the Arduino is then uploaded with the Standard Firmata microcontroller library (link), which allows for the microcontroller to interpret midi messages over serial.

(Communications Diagram)

*** Server side programming - node.js: express, logfmt, johnny-five and socket.io

The server, a small computer connected to the microcontroller, manages the major communication aspects of the installation, those being communication with the arduino, handling html web page requests and bi-directional webSocket communication with users once the page is sent. These three aspects are each handled within the node.js server-side javascript language by three module libraries,  johnny-five (microcontroller messaging), express(serving dynamically generated web-pages) and socket.io (webSockets management). In addition to this a small logging system is used to store user behaviour for later analysis and a database and archiving system exist to store user messages and video archives.

*** Johnny-Five (link)

The Johnny-Five library allows node.js to communicate with the Microcontroller by sending midi messages over the serial bus to the arduino. The requirements for the arduino in this instance are to register any floor sensor button presses, log them and then send an ‘on’ message to the 12v LED strip corresponding to the panel. The second requirement is to also send this message on to the webSocket management system, to be broadcast to all users. The final requirement is to also receive any messages from webSockets that direct the microcontroller to turn its LEDs on and do so. This third requirement enables the arduino to receive messages from remote participants, in this case so that visitors to the web page can control the installations light and sound by hovering over different buttons, simulating in-person participation.

(img 10 liner johnny-five code snippet)

*** express

Users who visit a web page a served a web page from the installations computer. This page contains the current user numbers of the chat room as well as the necessary authentication tokens for them to use the video chat. To provide the dynamic content the express middleware generates the html necessary. In this case the process is relatively simple, with the content being a  largely static page augmented with dynamically generated user tokens and statistics, as well as the last ten chat messages as retrieved from the database.

*** socket.io (link)

The socket.io library manages webSockets providing a more manageable abstraction for dealing with aschronous realtime messages. As the name implies, the library forms the core of the input/output messaging system of the installation by relaying messages in real time between disparate users and the server. The library can therefore manage all aspects of the chat application and user hover actions. Keeping track of users and their states and broadcasting these messages to all participants as well as broadcasting button triggers on the stairs to all website users.

*** Logging

A simple but key aspect is the ability to accurately log events for later analysis and compositional practice.. In this case a user logging on hovering over of standing on a  step are all given a date and time stamp then logged to a text file. Further user monitoring is handled on the client side by cloud based services firebase.io (link) and openTok (link).

*** Database & Archiving

Chat messages are logged to the cloud base fiebse service as they are received. This provides a complete text archive of all messages that can be acessed using an api from anywhere. Allowing the server to send clients the last ten messages to provide context and possibilities for analysis of the data to inform compositions. Similarly the server-side aspects of the openTok real-time-communication for video library offer a convenient way to archive video chat usage, which is then uploaded to a cloud-based storage instance provided by providers such as microsoft azure or any cloud provider that is currently offering discount cloud computing such as amazon ec2.

*** Client Side Web Programming - Chat, Video and Web Audio


The web server provides two web pages, one outwardly facing root of the web site, which serves the main client side application, a chat room with real time audio/video communication. The second page (henceforth referred to as the ‘host’ page) is served is at  an undisclosed url that provides audio functionality for the staircase and intended only for use in a scenario where a computer is connected to a webcam, speakers and microphone, although the possibilities of ‘hacking’ the host page is left open due to its publicly accessible address.

The ‘host’ page is primarily designed to contain a web audio API ‘audiocontext’ (link to appendix describing web audio api) that is controlled by webSocket messages to turn gain nodes on and off, a buffer and gain node corresponding to each step. This buffer initially contains a long (8 minutes or more) field recording. As users step on floor sensors or web client users hover over a set of 8 boxes , the corresponding gain node of a stair is un-muted.

For further explanation of the webAudio API system please see appendix 1.

(webAudio context diagram of internal signal flow)

The ‘host’ pages user functionality is minimal and specifically designed around the needs of the installation, providing appropriate responses to websocket messages by raising the gain of audio streams if told to by the server or another client. Despite the possibility of

(Video of ‘host’ page demo showing gain being added on step or user hover)


* WRITE Parasite Two


* WRITE Parasite Three


* WRITE Parasite Four


* WRITE Conclusions

  Question of even presenting the material. Is digital art a 'performance', I would argue it is, and that there is a neglected temporality.

  Danger is in emphasising mastry over and about understanding. How over why. Computers are always social.

  Technology as more medium than instrument, instrumental thinking as problematic.
is particular association is identified in “The Question Concerning Technology,” where Heidegger says that as long as we perceive “technology as an instrument, we
remain held fast in the will to master it.”9 A similar theme is taken up and examined by Heidegger in What is Called Thinking?10 Within this text, Heidegger pronounces that Nietzsche’s overman
represents the embodiment of pure technological being, insofar as the overman’s will is a will that
strives to dominate and master anything that is other.11 Heidegger feels that the overman is not an anomalous phenomenon in the modern technological age. All those who live under the sway of modern technology have to confront this reality. Within the periphery of the epoch of modern
technology, “the only thing we have left is purely technological relationships.”12

  The end goal is the hope tat users will envisage teh ways in which existing social engagements can be 're-tooled'. The 'hack' of technology is often not highly technical, instead it is a re-visioning of what a technology could be useful for.

communications technology and musical practice hold much in the way of a common history, converging and

the following works are a study in the relationship and possibilities in the spaces between communication technology and artistic practice.

on a personal level one piece of anecdotal evidence that i have noticed is the large number of programmers and ict (informatin communicatons technolgy) workers that are musicians, composers or disc.

The other piece of anecdotal evidence is the predisposition for composers toward computer programming and electronics.


* WRITE Extra Notes

*** Look at study on Links

jockeys[fn:51].
*** WRITE Graph of structure of Computationality

Networked Experience() ->
Abductive Aesthetics() ->
= Computationality ()
both combine into set of qualities

(Berry on Twitter [p. 76])As a form of computational media that is highly social, it presents an interesting case study in relation to our public/private experiences of communication through a computational platform.

   In this respect human relationships with technology occupy a somewhat vexed space, with technology seen as both 'means to an end', a tool of progress or improvement, yet perhaps more importantly technology is also a medium through which we experience the world.

* Footnotes

[fn:1] Waddington 576-577

[fn:2] (Kitchin 2011: 946)

[fn:3] Think python p. 7

[fn:4] DEFINITION NOT FOUND: fn:4

[fn:5] Wikipedia social computing https://en.wikipedia.org/wiki/Social_computing

[fn:6] From "Social Computing", introduction to Social Computing special edition of the Communications of the ACM, edited by Douglas Schuler, Volume 37 , Issue 1 (January 1994), Pages: 28 - 108

[fn:7] From "Social Computing", introduction to Social Computing special edition of the Communications of the ACM, edited by Douglas Schuler, Volume 37 , Issue 1 (January 1994), Pages: 28 - 108

[fn:8] Theories of the Digital

[fn:9] 'Critical Theory and the Digital'

[fn:10] Heidegger notes in /Being and Time/ that the priveleging of the present has a *parasitic* relationship with the concept of time. This could be extended.

[fn:11] heidegger qct

[fn:12] Enframing Heidegger p.2

[fn:13] Second ceoncealment Heidgger

[fn:14] description of links between software and constructionism

[fn:15] Waddington 576

[fn:16] ref to dependdence on human actors in cybersyn

[fn:17] Streams Programming Languages

[fn:18] explainng Heidegger

[fn:19] AllYOu need is data DTD

[fn:20] Pattern Aesthetics

[fn:21] the new Aesthetics

[fn:22] google autocomplete suggestions description link

[fn:23] link between abductive reasoning and ai.

[fn:24] link to uses of term

[fn:25] link to new aesthetic site / files

[fn:26] idea inspired by frocki's first film.

[fn:27] link to weiner

[fn:28] link de landa, berry.

[fn:29] idea taken from the talk,"the web that wasn't" )[[webthatwasnt][twtw]]

[fn:30] link to deetails on javascript streams

[fn:31] article about uses of early phonograph

[fn:32] edina 64

[fn:33] whats a daemon yo.

[fn:34] berry 10

[fn:35] berry 10

[fn:36] softwareised society, link opening of phil of software on dependance on software for survival. berry p.

[fn:37] berry, p. 6.

[fn:38] berry and deleuze, p. 18.

[fn:39] berry p.62

[fn:40] software is eating the

[fn:41] link to treer main history book / topics

[fn:42] stoch to xenakis quote

[fn:43] link five eyes surveillance

[fn:44] def of

[fn:45] link to classic essay about design of saftware informed

[fn:46] any links to this? there was a bit from deland

[fn:47] sousveilance

[fn:48] foucoult link, design of software and oppression

[fn:49] functions in programming.

[fn:50] computers and society

[fn:51] u[fn:4] http://rhizome.org/editorial/2014/oct/22/big-data-little-narration/
