* Reading Notes
	
*How we got to now, what shapes the way that we think about computers. Meditation n the popular imagination and its limits. Argue about the silencing of the social.
 ~rhetoric of systems, communities and information flow.~259

** Counterculture to Cyberculture
*** 176
...
*** 180
		Negroponte - "Some of us enhot a privileged existence where our work life and our leisure life are almost synonymouse,: he told Brand. "Moer and more peopple I think can move into that position with the coming of truely intimate technology
*** 204
		In the pages of _Out of Control_the lone hunter of the _Whole Earth Catalog_ had become and entrepeneur... Alnmost thrirt years earlier, thousands of young, highly educated Americans had tromped off into the wilderness seeking to build and egalitarian, fun-loving world. Today, suggested Kelly, they should look to technology and the economy for satisfaction...

		They should do so, he argued, becase the world itself was an information system. In his view, to manipulate computers and to manipulate information was not simply to hold down a job; it was to gain access toa  hidden world, to live by its laws, and to become in a sense a Comprehensive Designer of one's own fate. In that sense, Kelly's vision echoed the New Communalists' celebration of consciousness. It also resuscitated the commmune dwellers' disregard for the demands of the material world. In the 1960s, many had set out for rural America with little sense of the embodied labor that building their new society might take and little feel for the work already done by those among who they settled. In the 1990s, as a  number of critics have noted, Kelly's doctrine of cyberrevolutionism gave a potent ideologiical boost to executives seeking to outsource labour, automate industrial processes, and decrease the stability of these workers employment. Throughout his book, Kelly underplayed the work of embodied labour, celebrated intellect and collaborative styles associated with intellectual institutions, and so offered a model of a world inhabited exclusively by freelancing elites. IN the early 1990s, as in the late 1960s, that turn away from the material world helped legitimate the authority of those who controlled information and information systmes by rendering invisible those who did not. 

		At the same time, the turn toward imagining the world in terms of dematerialized networks of information helped assuage the increasing sense of helplessness among executives themselves. On the one hand, like scientists at the Rad Lab a half centruy earlier, executives could call on the rhetoric of cybernetics to justify the pursuit of their professional goals. Like the cold warrors who had long ago scenned ther computer screens for signs of incoming bombers, they could imagine the world as an information system and themselves as monitors of that system. Thanks to the computers they were so rapidly installing in their firms, they could see farther, plan more effectively, and perhaps manage their firms "as gods". On the other hand, they could begin to accept that they lacked precisely the sorts of power that Stewart Brand and others of his generation imagined belonged to corporate leaders. In the late 1980s and early 1990s, despite the spke in executive incomes and the broad-based movement of wealth towards those at the top of the social ladder, many executives laboured under a sense that they were surrounded by forces ~beyond~ their control. ... "the missing ingredient in biology... is values"
		
*** 219
		Quittner summed up her argument this way: "The Net, the very network itself, is merely a means to an end. THe end is to reverse-engineer government, to hack Politics down to its component parts and fix it." 
		The urge to "hack" politics by bringing governance down to a manageable local level and by basing social integration on technologically facilitated forms of consciousness was one of the driving impulses behind the New Communalist movement.
*** 224
*** 229
*** =237=
		their techno-utopian social vision in fact reflected the slow untwiing of two far deeper transforamtion in American society. The first of these was technological. Over the previous forty years, the massive, stand alone calculating machines of the cold war had become desktop computers, linked to one another ina a vast network of communications that reached into almost every corner of the civilian world. This shift incomputing technology took place, however, alongside a second, cultural transformation. In the late 1950s, Stewart Brand and others of his generation had come of age fearing that they would soon be absorbed into an unfeeling...

=By the late 1990s, Brand and his Whole Earth colleagues had repeatedly linked these technological and cultural chenges and in the process had helped turn the terms of thei generational search into the key frames by which the American public understood the social possibiliteis of computers and computer networking... desktop computers had come to be seen as "personal" technology. In keeping with the New Communalist ethos of tool use, they promised to transform the individual consciousness and society at large. Thanks to the citizens of the WELL, computer-mediated communication had been reimagined in terms of disembodied, communal harmony and renamed virtual community. Cyberspace itself had been reimagined as an electronic frontier. Finally, in the 1990s, the social and professional networks o teh Global Business Network and Wired seemed to suggest that a new, networked form of economic life was emerging. Because of computer technologies, their expample implied, it was finally becoming possible to move through life not in heirachical beuracratic towers, but as memeber os flexible, temporary, and culturally congenial tribes.

In all of these ways, memebers of the Whole Earth network helped reverse the political valece of information and information technology and turn computers into emblems of countercultural revolution. At the same time, however, they legitimated a metamorphises within- and a widespred diffusion of- the core cultural styles of the miliutary-industrial-academic technocracy that their generation had sought to undermine. In the imagination of the young Stewart Brand and others like him, the middle-aged men who ran the corporations, universities, and governments of teh cold war had found themselves locked into rigid roles... throughout the military-industrial-academic complex responsible for developing America's defense technologies, a far more collaborative style was emerging.

.. Stewart Brand and teh Whole Earth network not only reconfigured the cultural status of information and information technologies as they moved from the government-funded, military-industrial research world into society at large; they also helped legitimate a parellel migration on the part of that world's cultural style. Moreover, they did so by embarcing the cybernetic theories of information, the universal rhetorical techniques,a dn teh flexible social practices born out the interdisciplinary collaborations of World War II. Like the designers of theat era's weapons research laboratories, Brand and his colleagues creted network forums in which members of multiple coial and technical communities could come together, collaborate, and , in the process, build shared understandings of their colective interests. Expressed first in local contact languages, these understandings were repeatedly exported from the forums themselves, either by forum members or by professional journalists in attendence. Like the laboratories that first gave rise to cybernetics, however, the forums produced more than new bits of rhetoric. They also produced new social networks nad, in Brand's case, new information systems, such as catalogs, meetings, and online gatherings. These sytems in turn hosted and helped to create new social and professional networks and at the same time modeled teh networks' governing ideals.=
*** 259
		Problems of homogenaity in leading this life...
*** 259-260
		in keeping with the vision's history as the universal rehorical tool with which cold war researchers claimed authority for their projects, the fact tht the social and the natural, the individual tand the institutional, the human and the machine could all be seen as refelctions of one another suggested that those who could most successfully decict themselves as aligned witht the forces of information could alos claim to be models of thoise forces. They could in fact claim to have a "natural" right to power, even as tehy disguised thir leadership witha  ~rhetoric of systems, communities and information flow.~

*** TODO add more 261
*** 262
		
