* Reading Notes

* Counter-culture to Cyberculture
** 176
	 On the development of the GBN (global business network) - Within the precinct of the Global Business Network and _Out of Control_, however, these organizations acquired a new political valence. They became models of a collaborative world, a world in which technologies were rendering information systems visible, material production processes irrelevant, and bureaucracy obsolete. Their executives and engineers also became visible stand-ins for the emerging corporate elect- entrepreneurial, technologically savvy, but socially and culturally conservative. Like the Communards of New Mexico and northern California, the scientists, futurists and entrepreneurs of the Global Business Network and _Out of Control_ constituted a highly educated, mobile and predominantly white elite.
** 180
	 Negroponte - "Some of us enjoy a privileged existence where our work life and our leisure life are almost synonymous, he told Brand. "More and more people I think can move into that position with the coming of truly intimate technology
** 204
	 In the pages of _Out of Control_the lone hunter of the _Whole Earth Catalog_ had become and entrepreneur... Almost thirty years earlier, thousands of young, highly educated Americans had tromped off into the wilderness seeking to build and egalitarian, fun-loving world. Today, suggested Kelly, they should look to technology and the economy for satisfaction...

	 They should do so, he argued, because the world itself was an information system. In his view, to manipulate computers and to manipulate information was not simply to hold down a job; it was to gain access to a  hidden world, to live by its laws, and to become in a sense a Comprehensive Designer of one's own fate. In that sense, Kelly's vision echoed the New Communalists' celebration of consciousness. It also resuscitated the commune dwellers' disregard for the demands of the material world. In the 1960s, many had set out for rural America with little sense of the embodied labor that building their new society might take and little feel for the work already done by those among who they settled. In the 1990s, as a  number of critics have noted, Kelly's doctrine of cyberrevolutionism gave a potent ideological boost to executives seeking to out-source labor, automate industrial processes, and decrease the stability of these workers employment. Throughout his book, Kelly underplayed the work of embodied labor, celebrated intellect and collaborative styles associated with intellectual institutions, and so offered a model of a world inhabited exclusively by free-lancing elites. In the early 1990s, as in the late 1960s, that turn away from the material world helped legitimate the authority of those who controlled information and information systems by rendering invisible those who did not.

	 At the same time, the turn toward imagining the world in terms of dematerialized networks of information helped assuage the increasing sense of helplessness among executives themselves. On the one hand, like scientists at the Rad Lab a half century earlier, executives could call on the rhetoric of cybernetics to justify the pursuit of their professional goals. Like the cold warriors who had long ago scanned their computer screens for signs of incoming bombers, they could imagine the world as an information system and themselves as monitors of that system. Thanks to the computers they were so rapidly installing in their firms, they could see farther, plan more effectively, and perhaps manage their firms "as gods". On the other hand, they could begin to accept that they lacked precisely the sorts of power that Stewart Brand and others of his generation imagined belonged to corporate leaders. In the late 1980s and early 1990s, despite the spike in executive incomes and the broad-based movement of wealth towards those at the top of the social ladder, many executives labored under a sense that they were surrounded by forces ~beyond~ their control. ... "the missing ingredient in biology... is values"

** 219
	 Quittner summed up her argument this way: "The Net, the very network itself, is merely a means to an end. The end is to reverse-engineer government, to hack Politics down to its component parts and fix it."
	 The urge to "hack" politics by bringing governance down to a manageable local level and by basing social integration on technologically facilitated forms of consciousness was one of the driving impulses behind the New Communalist movement.
** 224
** 229
** =237=
		their techno-utopian social vision in fact reflected the slow entwining of two far deeper transformation in American society. The first of these was technological. Over the previous forty years, the massive, stand alone calculating machines of the cold war had become desktop computers, linked to one another in a vast network of communications that reached into almost every corner of the civilian world. This shift in computing technology took place, however, alongside a second, cultural transformation. In the late 1950s, Stewart Brand and others of his generation had come of age fearing that they would soon be absorbed into an unfeeling...

=By the late 1990s, Brand and his Whole Earth colleagues had repeatedly linked these technological and cultural changes and in the process had helped turn the terms of their generational search into the key frames by which the American public understood the social possibilities of computers and computer networking... desktop computers had come to be seen as "personal" technology. In keeping with the New Communalist ethos of tool use, they promised to transform the individual consciousness and society at large. Thanks to the citizens of the WELL, computer-mediated communication had been re-imagined in terms of disembodied, communal harmony and renamed virtual community. Cyberspace itself had been re-imagined as an electronic frontier. Finally, in the 1990s, the social and professional networks o the Global Business Network and Wired seemed to suggest that a new, networked form of economic life was emerging. Because of computer technologies, their example implied, it was finally becoming possible to move through life not in heirachical bureaucratic towers, but as member of flexible, temporary, and culturally congenial tribes.

In all of these ways, members of the Whole Earth network helped reverse the political valence of information and information technology and turn computers into emblems of counter-cultural revolution. At the same time, however, they legitimated a metamorphosis within- and a widespread diffusion of- the core cultural styles of the military-industrial-academic technocracy that their generation had sought to undermine. In the imagination of the young Stewart Brand and others like him, the middle-aged men who ran the corporations, universities, and governments of the cold war had found themselves locked into rigid roles... throughout the military-industrial-academic complex responsible for developing America's defense technologies, a far more collaborative style was emerging.

.. Stewart Brand and the Whole Earth network not only reconfigured the cultural status of information and information technologies as they moved from the government-funded, military-industrial research world into society at large; they also helped legitimate a parallel migration on the part of that world's cultural style. Moreover, they did so by embracing the cybernetic theories of information, the universal rhetorical techniques,a and the flexible social practices born out the interdisciplinary collaborations of World War II. Like the designers of that era's weapons research laboratories, Brand and his colleagues created network forums in which members of multiple coial and technical communities could come together, collaborate, and , in the process, build shared understandings of their collective interests. Expressed first in local contact languages, these understandings were repeatedly exported from the forums themselves, either by forum members or by professional journalists in attendance. Like the laboratories that first gave rise to cybernetics, however, the forums produced more than new bits of rhetoric. They also produced new social networks nad, in Brand's case, new information systems, such as catalogs, meetings, and online gatherings. These sytems in turn hosted and helped to create new social and professional networks and at the same time modeled teh networks' governing ideals.=
** 259
	 Problems of homogenaity in leading this life...
** =259-260=

	 in keeping with the vision's history as the universal rehorical tool with which cold war researchers claimed authority for their projects, the fact tht the social and the natural, the individual tand the institutional, the human and the machine could all be seen as refelctions of one another suggested that those who could most successfully decict themselves as aligned witht the forces of information could alos claim to be models of thoise forces. They could in fact claim to have a "natural" right to power, even as tehy disguised thir leadership with a  ~rhetoric of systems, communities and information flow.~
	 ...
	 It was this clain that Stewart Brnad and his colleagues modeled for their clients at the Global Business Network, and it was this claim that the writers of _Wired_ bolstered by depicting subjects such as Esther Dyson and George Gider as people who spoke or acted like computers. As the communcards of the back-to-the-land movement had once argued that they were forerunners of a new, more egalitaritian society on the basis of their being in touch with a shared consciousness, the information consultants of the 1990s asserted that the INternet modeled not only an egalitarian future, but their own, existing lives. In touch witht the flow of information, they could safely represent themselves as a "digital generation" - or, in a term much used at the time, as "digerati".

	 ~The rhetoric of peer-to-peer informationalism, however, much like the rhetoric of consciousness out of which it grew, actively obscures the material and technical infrastructures on which both the Internet and the lives of the digital generation depend. Behind the fantasy of unimpeded information flow lis the reality of millions of plastic keyboards, silicon wafers, glass-faced monitors, and endless miles of cable. All of these technologies depend on manual laborers, first to build them and later to tear them apart. This work remains extraordinarily dangerous, first to those who handle the toxic chemicals required in manufacture and later to those who live on the land, drink the water, and breathe the air into which those chemicals eventually leak.~
** =261=
	 Like the communareds of the 1960s, the techno-utopians of the 1990s denied their dependence on any but themselves. At the same time, they developed a way of thinking and talking about digital technology from within which it was almost impossible to challenge their own elite status.[fn:1] On the communes of the 1960s, the rhetoric of consciousness and community contained little in the way of language with which to describe, let alone confront, a less-than-egalitarian distribution of resources. The same was true of information theory and the universal rhetoric of cybernetics. In both cases, human power was an individual possession, born of the proper use of technologies for the amplification of awareness through access to information. I the writings of the _Wired_group of the 1990s, this model of power and therhetoric on which it depended reappeared. Both persist today throughout discussions of computer mediated communication. Even as they conjured up visions of a disembodied, peer-to-peer utopia, and even as they suggested that such a world would in fact represent a return to a more natural, more intimate state of being, writers such as Kevin Kelly, Ehter Dyson and John Perry Barlow deprived their many readers of a language with which to think about the complex ways in which embodiement shapes all of human life, about the naural and social infrastructures on which that life depends, and about the effects that digital technologies and the network mode of production might have on life and its essential infrastructures.

for these writers, the arrival of the Internet marked not only the end of the industrial era, but the end of history itself. Forty years earlier Stewart Brand and otehrs of his generation had been among the first to come of age in a world that could, as a whole, be destroyed n a matter of minutes. As young adults, although they turned away frm the war-making mind-set, the bureacratic structures, and the partitioned psyches that they imagined characterised life in the military-industrial reserch establishment, many embraced its information theories, its collaborative, experimental orientation, and its underlying world saving mission. Like the atomic scientists at Los Alamos, they would become comprehensive Designers, of their own fates and, by vanguard example, of the fates of mankind. By 1968 more than a few communards beleived, as Steward Brand put it, that "We are as gods and we might as well get good at it."

In his 1968 voluem _The Young Radicals_, Kenneth Kenniston looked on the fractures within the youth movements of the day and wondered how they might ultimately shape American society. "How and whether [the] tension between alienation and activis, is resolved seems to me of the greatest importance," he explained. In the short term, Keniston feared that antiwar activists wuold become frustrated at the failure to stop the conflict in Vietnam and would retreat into academe and the professions. "The field of dissent would be left to the alienated," he wrote, "whose intense quest for _personal_ salvation, meaning, creativity and revelation dulls their perception of the public world and inhibits attempts to better teh lot of others." IN recent years, Keniston's fears seem to have come true, particularly in discussions of the social potential of the Internet and the World Wide Web. To many, these technologies seem to promise what strobe lights and LSD of the Trips Festival once offfered the hippies of the Haight: access to a vision of the patterns underlying the world, and by means of that vision, a way to join one's life to them and to enter a global, harmonious community of mind. As both information technologies and the network mode of production have spread across the landscape, they have been celebrated as sites of personal and collective salvation. And to that extent, they have rendered their believers vulnerable to the material forces of the historical moment in which they live.

And yet, they have preserved a deeper dream as well. As they set off for the hills of New Mexico and Tennessee, the communards of the back-to-the-land movement hoped to build not only communities of consciousness, but real, embodied towns. Most failed- not for lack of good intentions, nor even for lack of tools, but for lack of attention to politics. To the extent that Stewart Brand and the Whole Earth group have succeeeded in linking the ideals of those whom Kenneth keniston called the alienated to digital technologies, ~they have allowed computer users everywhere to imagine their machines as tools of personal liberation.~ O

* Philosophy of code

** 2
This transforms our everyday live into data, a resource to be used by others, usually for profit, which Heidegger terms /standing-reserve[fn:2]/.

** 3
Compters are entangled with our lives n a multitude of different, contradictory and complex ways, providing us with a social milieu that allows us to live in a society that increasingly depends on information and knowledge.

** 4
As software increasingly structure the contemporary world, curiously, it also withdraaws, and becomes hard and harder for us to focus on as itis embedded, hidden, off-shored or merely forgotten about.

** 14
The computational device, as an algorithmic totality, is in a constant state of exception from multiple events which must be attended to, that is, the device is constantly interrupted by a parliament of things or users. THe seemingly end-directed nature of computational processes may actually be constantly deferred internally, that is, never reaching a final goal. In a certain sense, this is an agnostic form of communicative action where devices are in a constant stream of data flow and decision-making which may only occasionally feedback to the human user.
For computer scientists, it is the translation of the continuum in to the discrete that marks the connndition of possibility for computationality... To mediate an object, a computational device requires that it be translated.

** 15
in cutting up the world in this manner, information about the world has to be discarded in order a store a representation within the computer... The other side of the coin, of course, is that these subtractive methods of understanding reality (episteme) produce new knowledges and methods for the control of reality (techne).
For objects in the world to be compuational requires that they offer a certain set of affordances facilitated through the operation of computer code. This is managed through the writing of code that determines certain functions that the software is engineer to perform. These can be at the level of the software itself, and hence invisible to the user directly ( for example application programming interfaces or APIs ), or presented to teh user through a visual interface which allows the user to determine what it does, its /affordance/. To distinguish between the two, it is useful to think of hidden /affordances/ and /visible/ affordances. That is, with visible affordances,
"The valie is clear /on the face of it/... The postbox 'invites' the mailing of a letter, the handle 'wants to be grasped', and things 'tell us what to do with them '(Gibson 1988: 136)"
* Cybernetic Revolutionaries
** 88
The room later broke new ground in interface design, not because of its technical newness but because ot the priority its designers gave to the human operator. "Special attention will be paid to the development of man-machine interfaces," Beer specified, focusing once agian on the user and prioritizing human understanding over technological flashiness. He continued, "The Operations room should be thought of /NOT/ as a room containing interesting bits of equipment /BUT/ as  a control machine comprising men and artifacts in symbiotic relationship. It needs designing as a totality and as an operational entity."(69) The operations room would later emerage as the iconic image of Project Cybersyn and the symbolic heart of the project.
** 91
Scholars such as Lawrence Lessig, Langdon Winner, and Batya Friedman have shown that values can be designed into technologies, meaning that they can uphold certain principles by enabling certain types of behavior while discouraging others.(75)
** 133
   The State Technology Institute had a rather sophisticted understanding of how technological artifacts could uphold particular configurations of power, either by enriching one class at the expense of another or by promoting unjust economic relations between developed and developing nations. Bbut engineers from the State Technology institute did not extend such criticism to the scientific techniques that they used, which they viewed as free of political bias.
** 159-160
he (Beer) concluded that giving workers control of technology, both its use and design, could constitute a new form of worker empowerment.
This assertion differed substantially from how other industrial studies of the day approached the relationship of computer technology and labour in twentieth century production. Such studies, expecially those inspired by Marxist analysis, often presented computers and computer-controlled machinery as tools of capital that automated labor, led to worker deskilling, and gave management greater control of the shop floor. In /Labor and Monopoly capiltal/ (1974), Harry Braverman credits such machinery "as the prime means whereby production may be controlled not by direct producer but by the owner and the representatives of capital" and cites computer technology as routinizing even highly skilled professions such as engineering.
In the 1980s, historian David Noble aslso argued that the introduciton of numerical control technology in factory work stripped workers of their abilities to mentally and physically control factory machninery and gave management greater control of labor. "Because technology is political, it must be recognised that... new technology will invariably constitute extensions of power and control," namely, of managers over workers. That such technologies might be turned to humane ends is a dangerous delusion," he concluded.(54)
In the 1950s Nobert Wiener, author of /Cybernetics/, beleived computers would usher in a second industrial revolution and lead to the creation of an automatic factory. In /The Human Use of Human Beings/(1954) he worries that automated machinery "is the precise economic equivalent of slave labor. Any labor that competes with slave labor must accept the economic conditions of slave labor"(56)
** 161
Beer's proposal bears a close resemblance to the work on participatory design that emerged from the social demoratic governments of Scandanavia in the 1970s. The history of participatory design is often tied to Scandanavian trade union efforts to empower workers during that decade... participatory design used the primacy of management as a starting point then tried to change the dynamics of the labor-capital relationship by changing the social practices surrounding design and use of technology. Initially, this involved educating workers about the technology in use in the workplace so that they could participate in decisions about its use. During the 1980s and 1990s, though, participatory design evolved into a set of methods, theories and practices for involving workers in the design of the computer systems that they used. Proponents of participatory design argued that such practices resulted not only in the creation of better computer systems, in the sense that they better suited workers needs and increaded their ability to get the job done, but also in the creation of more ethical systems that took into account the interests of stakeholders other than management.
** 207 =Important=
But it is important to keep in mind that oftentimes these different interpretations of Cybersyn were not referring to the same system. Although it is tempting top reduce a technological system to its hardware, historians of technology have shown that technological systems are a "seamless web" of social, institutional and technological relationships.(122) Many of the different interpretations of Project cybersyn present in this chapter resulted from Cybersyn's being treated as different sociotechnical systems.
For example, Beer wanted to change ship floor power dynamics by alterning the relationship between workers and technolgists. He wanted to institutionalize a decentralized approach to control by changing how hierachies of command funcitoned within an organisation. And he wanted to change decision-making practices by giving managers access to real-time information, recognizing that the colleciton and transmission of this information depended mostly on human labor. Altering any of tehse social and organizational relations would result in a very different sociotechnical systems from the one Beer proposed. Thus configured, the system could support different configurations of power and different political goals.
** 230
His (Maturana) 1959 work with Jerry Lettvin, Warren McCulloch, and Walter Pitts analyzed the frog's optical system and concluded that what a frog sees is not reality per se but rahter a construction assembled by the frog's visual system. What the frog sees is therefore a product of its biological structure. This distinction formed the foundation for much of Maturana and Varela's  later work in biology and cognition in the 1960s and 1970s, and later inspired the two biologists to break with traditional claims of scientific objectivity and emphasize the role of the observer. One of Maturana's best known claims-"Anything said is siad by an observer"-illustrates this point(21)
** 231 =Flores Computers and Cognition=
/Understanding Computers and Cognition/ begins by critiquing the rationalist assumption that an objective, external world exists. The critique builds on the ideas of Heidegger, Searle, Maturana, J.L Austen, and Hans-Georg Gadamer to show that knowledge is teh result of the interpretation and depends on the past experiences of the interpreter and his or her situation in tradition. Winograd and Flores then argue that because computers lack such experiences and traditions, they cannot replace human beings as knowledge makers. "The ideal of an objectively knowledgable expert must be replaced with a recognition of the importance of background,"(32) Winograd and Flores write. "This can lead to the design of knowledgable community."(32) Moreover, conputer designers should not focus on creating an artifact but should view their labours as a form of "ontological design." Computers should relect who we are and how we interact witht he world, as well as shape what we can do and who we will become... It is now considered a key text inthe field of human-computer interaction.

* Critical Theory and the Digital
** 1
     The aim is to understand how we can think about computation as part of the social totality and also provide teh means to develop an immanent critique in relation to it. Ther is still mnuch work to be done in humanities and social sciences to understand and critique the computational, and it is a social phenomenon that is accelerating in its growth and ubiquity.

/our societies are increasingly becoming computational, and with it the atttendant tendency of computational systems to reify all aspects of everyday life, it is crucial that we attend to the mechanization of reification and the dangers presented when these processes crystalize into systems , institutions and consciousness itself. The reified world is 'smart', digital and is increasingly colonized by computationally enhanced networks, objects and subjects./

A new /industrial internet/ is emerging, a computational, real-time streaming ecology that is reconfigured in terms of digital flows, fluidities and movement. In the new industrial internet the paradigmatic metaphor I want to use is the real-time streaming technologies and the data flows, processual stream-based engines and the computal interfaces that embody them. This is stop thinking about the digital as something static and  instead consider its 'trajectories'. Here I am thinking about the way in which scripts function to create loops and branches, albeit of a highly complex form, and create a stable 'representation', wheich we often think of as a digital 'object'.
** 8
noticeable shifts in the mode of production and the mdes of communication increasingly challenge our actual understanding of humanity /qua/ humanity as reflectied in debates over reading skills, neuromarketing, behavioral nudges and so forth. These digital elements are thought to soften the boundaries between human and machine and pose questions for philosophers and theorists about human autonomy and distinctiveness (see Feuler 2011; Steigler 2010)
** 10
the digital is in any ways the creation of a constellation of standards, canonical ways of passing around discrete information and data, that creates what we might call /witnesses/ to the standard - software enforcing the disciplinary action of these standards, such as Application programming Interfaces (APIs). Owning and controlling standards can have a political economic advantage in a post-Fordist society, and much jostling by multinational corperations  and governments is exactly over the imposition of certain kinds of technical standards on the internet, or what Galloway calls protocol.
** 11
   the norms and values of the computational economy can be prescribed quite strongly as a society of control limitng action, thought and even knowledge. This we might understand as the danger of a transition from a rational juridical epistemeology to an /authoritarian-computational/ epistemeology.

* Footnotes

[fn:2] Heid 1993a: 322
